

#RequireAdmin
#include <Array.au3>
#include <File.au3>

Global $SciTEUserDir
Global $sUserPath

_GetAutoitPath()

Global $SciTEUser_Content = StringStripWS(FileRead($SciTEUserDir & "\SciTEUser.properties"), 3)
Global $sCallTipPath = $SciTEUserDir & "\au3.user.calltips.api"
Global $sKeyWordPath = $SciTEUserDir & "\au3.userudfs.properties"
Global $aCallTip, $cc
Global $i_Updated = 0, $i_Imported = 0
_FileReadToArray($sCallTipPath, $aCallTip)
If IsArray($aCallTip) = False Then
	Local $aCallTip[1] = [0]
EndIf

_ArraySort($aCallTip, 0, 1)
Local $index_start = $aCallTip[0]

GetStr()
;~ Exit
_WriteImGuiUDF()
_ChangeUDFColor()

If $i_Updated > 0 Or $i_Imported > 0 Then
	_Save_Exit_UCT()
	MsgBox(64, "ImGui-AutoIt setup", "Setup completed." & @CRLF & @CRLF & " - Updated: " & $i_Updated & @CRLF & " - Imported: " & $i_Imported)
Else
	MsgBox(64, "ImGui-AutoIt setup", "No change has been made.")
EndIf

Local $SciTE_hwnd = WinGetHandle("DirectorExtension")
If $SciTE_hwnd Then
	Opt("WinSearchChildren", 1)
	SendSciTE_Command(0, $SciTE_hwnd, "reloadproperties:")
EndIf


Func _WriteImGuiUDF()
	_Write_CallTip("_ImGui_ShutDown", 					'_ImGui_ShutDown() Shutdown ImGui and close the dll handle.')
	_Write_CallTip("_ImGui_SetWindowTitleAlign", 		'_ImGui_SetWindowTitleAlign($x = 0.5, $y = 0.5) Value of $x and $y is from 0 -> 1  (0.5 mean center)')
	_Write_CallTip("_ImGui_EnableViewports", 			'_ImGui_EnableViewports($enable = True) Enable multiple viewports. Use before _ImGui_GUICreate')
	_Write_CallTip("_ImGui_EnableDocking", 				'_ImGui_EnableDocking($enable = True) Enable docking a window to another')
	_Write_CallTip("_ImGui_GUICreate", 					'_ImGui_GUICreate($title, $w, $h, $x = -1, $y = -1, $style = 0, $ex_style = 0) Create the main window')
	_Write_CallTip("_ImGui_PeekMsg", 					'_ImGui_PeekMsg() Return False when the user click the close button')
	_Write_CallTip("_ImGui_Begin", 						'_ImGui_Begin($title, $close_btn = False, $flags = $ImGuiWindowFlags_None) Create a window, if $close_btn = true, then return false when being closed, else always return true')
	_Write_CallTip("_ImGui_BeginChild", 				'_ImGui_BeginChild($text, $w = 0, $h = 0, $border = False, $flags = $ImGuiWindowFlags_None) Create a child window')
	_Write_CallTip("_ImGui_End", 						'_ImGui_End() End the window, must call after _ImGui_Begin')
	_Write_CallTip("_ImGui_EndChild", 					'_ImGui_EndChild()  End the child window, must call after _ImGui_BeginChild')
	_Write_CallTip("_ImGui_Button", 					'_ImGui_Button($text, $w = 0, $h = 0) Create a button, return true if the button is clicked.')
	_Write_CallTip("_ImGui_InputText", 					'_ImGui_InputText($label, ByRef $buf, $flags = $ImGuiInputTextFlags_None, $buf_size = 128000) Return true if the user has typed anything')
	_Write_CallTip("_ImGui_InputTextMultiline", 		'_ImGui_InputTextMultiline($label, ByRef $buf, $size_x = 0, $size_y = 0, $flags = $ImGuiInputTextFlags_None, $buf_size = 128000) Return true if the user has typed anything')
	_Write_CallTip("_ImGui_InputTextWithHint", 			'_ImGui_InputTextWithHint($label, $hint, ByRef $buf, $flags = $ImGuiInputTextFlags_None, $buf_size = 128000)  Return true if the user has typed anything')
	_Write_CallTip("_ImGui_Text", 						'_ImGui_Text($text) Just a simple text')
	_Write_CallTip("_ImGui_CheckBox", 					'_ImGui_CheckBox($text, ByRef $active) Return true if the value has changed')
	_Write_CallTip("_ImGui_BeginFrame", 				'_ImGui_BeginFrame() Begin a new frame')
	_Write_CallTip("_ImGui_EndFrame", 					'_ImGui_EndFrame($clear_color = 0xFF738C99) $clear_color: background color')
	_Write_CallTip("_ImGui_StyleColorsDark", 			'_ImGui_StyleColorsDark() Set dark style color')
	_Write_CallTip("_ImGui_StyleColorsLight", 			'_ImGui_StyleColorsLight() Set light style color')
	_Write_CallTip("_ImGui_StyleColorsClassic", 		'_ImGui_StyleColorsClassic() Set classic style color')
	_Write_CallTip("_ImGui_IsWindowAppearing", 			'_ImGui_IsWindowAppearing() Check if window is appearing')
	_Write_CallTip("_ImGui_IsWindowCollapsed", 			'_ImGui_IsWindowCollapsed() Check if window is collapsed')
	_Write_CallTip("_ImGui_IsWindowFocused", 			'_ImGui_IsWindowFocused($flags = $ImGuiFocusedFlags_None) Check if window is focused')
	_Write_CallTip("_ImGui_IsWindowHovered", 			'_ImGui_IsWindowHovered($flags = $ImGuiFocusedFlags_None) Check if window is hovered')
	_Write_CallTip("_ImGui_GetWindowDrawList", 			'_ImGui_GetWindowDrawList() Get window draw list.')
	_Write_CallTip("_ImGui_GetWindowDpiScale", 			'_ImGui_GetWindowDpiScale() Get current window DPI scale')
	_Write_CallTip("_ImGui_GetWindowViewport", 			'_ImGui_GetWindowViewport() Get current window viewport')
	_Write_CallTip("_ImGui_GetOverlayDrawList", 		'_ImGui_GetOverlayDrawList() Get overlay draw list.')
	_Write_CallTip("_ImGui_GetBackgroundDrawList", 		'_ImGui_GetBackgroundDrawList() Get background draw list.')
	_Write_CallTip("_ImGui_GetForegroundDrawList", 		'_ImGui_GetForegroundDrawList() Get foreground list.')
	_Write_CallTip("_ImGui_GetWindowPos", 				'_ImGui_GetWindowPos() Get current window position. Return [x, y]')
	_Write_CallTip("_ImGui_GetWindowSize", 					'_ImGui_GetWindowSize() Get current window size. Return [x, y]')
	_Write_CallTip("_ImGui_GetWindowWidth", 					'_ImGui_GetWindowWidth() Get current window width')
	_Write_CallTip("_ImGui_GetWindowHeight", 					'_ImGui_GetWindowHeight() Get current window height')
	_Write_CallTip("_ImGui_GetMousePos", 						'_ImGui_GetMousePos() Get mouse position. Return [x, y]')
	_Write_CallTip("_ImGui_GetMousePosOnOpeningCurrentPopup", 	'_ImGui_GetMousePosOnOpeningCurrentPopup() Get mouse position on the current openning popup window. Return [x, y]')
	_Write_CallTip("_ImGui_GetMouseDragDelta",				 	'_ImGui_GetMouseDragDelta($button = $ImGuiMouseButton_Left, $lock_threshold = -1) Get mouse drag delta. Return [x, y]')
	_Write_CallTip("_ImGui_SetNextWindowPos", 				'_ImGui_SetNextWindowPos($x, $y, $cond = $ImGuiCond_None, $pivot_x = 0, $pivot_y = 0) Set next window position')
	_Write_CallTip("_ImGui_SetNextWindowViewport", 				'_ImGui_SetNextWindowViewport($id) Set next window viewport')
	_Write_CallTip("_ImGui_SetNextWindowSize", 				'_ImGui_SetNextWindowSize($x, $y, $cond = $ImGuiCond_None) Set next window size')
	_Write_CallTip("_ImGui_SetNextWindowSizeConstraints", 	'_ImGui_SetNextWindowSizeConstraints($size_min_x, $size_min_y, $size_max_x, $size_max_y) Set minimum and maximum size for the window')
	_Write_CallTip("_ImGui_SetNextWindowContentSize", 	'_ImGui_SetNextWindowContentSize($size_x, $size_y) Set next window content size')
	_Write_CallTip("_ImGui_SetNextWindowCollapsed", 	'_ImGui_SetNextWindowCollapsed($collapsed, $cond = $ImGuiCond_None) Collapse the next window')
	_Write_CallTip("_ImGui_SetNextWindowFocus", 		'_ImGui_SetNextWindowFocus() Set focus to the next window')
	_Write_CallTip("_ImGui_SetNextWindowBgAlpha", 		'_ImGui_SetNextWindowBgAlpha($alpha) Set next window alpha background, $aplha from 0 -> 1')
	_Write_CallTip("_ImGui_SetWindowPos", 				'_ImGui_SetWindowPos($pos_x, $pos_y, $cond = $ImGuiCond_None) Set current window position')
	_Write_CallTip("_ImGui_SetWindowSize", 				'_ImGui_SetWindowSize($size_x, $size_y, $cond = $ImGuiCond_None) Set current window size')
	_Write_CallTip("_ImGui_SetWindowCollapsed", 		'_ImGui_SetWindowCollapsed($collapsed, $cond = $ImGuiCond_None) Collapse the current window')
	_Write_CallTip("_ImGui_SetWindowFocus", 			'_ImGui_SetWindowFocus() Focus the current window')
	_Write_CallTip("_ImGui_SetWindowFontScale", 		'_ImGui_SetWindowFontScale($scale) Set current window font scale')
	_Write_CallTip("_ImGui_SetWindowPosByName", 		'_ImGui_SetWindowPosByName($name, $pos_x, $pos_y, $cond = $ImGuiCond_None) Set window pos by its name')
	_Write_CallTip("_ImGui_SetWindowSizeByName", 		'_ImGui_SetWindowSizeByName($name, $size_x, $size_y, $cond = $ImGuiCond_None) Set window size by its name')
	_Write_CallTip("_ImGui_SetWindowCollapsedByName", 	'_ImGui_SetWindowCollapsedByName($name, $collapsed, $cond = $ImGuiCond_None) Collapse a window by its name')
	_Write_CallTip("_ImGui_SetWindowFocusByName", 		'_ImGui_SetWindowFocusByName($name) Focus a window by its name')
	_Write_CallTip("_ImGui_GetContentRegionMax", 		'_ImGui_GetContentRegionMax() Get max content region. Return [x, y]')
	_Write_CallTip("_ImGui_GetContentRegionAvail", 		'_ImGui_GetContentRegionAvail() Get available content region. Return [x, y]')
	_Write_CallTip("_ImGui_GetWindowContentRegionMin", 	'_ImGui_GetWindowContentRegionMin() Get current window min content region. Return [x, y]')
	_Write_CallTip("_ImGui_GetWindowContentRegionMax", 	'_ImGui_GetWindowContentRegionMax() Get current window max content region. Return [x, y]')
	_Write_CallTip("_ImGui_GetItemRectMin", 			'_ImGui_GetItemRectMin() Get current item position. Return [x, y]')
	_Write_CallTip("_ImGui_GetItemRectMax", 			'_ImGui_GetItemRectMax() Get current item position + size. Return [x, y]')
	_Write_CallTip("_ImGui_GetItemRectSize", 				'_ImGui_GetItemRectSize() Get current item size. Return [x, y]')
	_Write_CallTip("_ImGui_GetWindowContentRegionWidth", 	'_ImGui_GetWindowContentRegionWidth() Get current window content region width')
	_Write_CallTip("_ImGui_GetScrollX", 					'_ImGui_GetScrollX() Get current scroll X')
	_Write_CallTip("_ImGui_GetScrollY", 				'_ImGui_GetScrollY() Get current scroll Y')
	_Write_CallTip("_ImGui_GetScrollMaxX", 				'_ImGui_GetScrollMaxX() Get max scroll X')
	_Write_CallTip("_ImGui_GetScrollMaxY", 				'_ImGui_GetScrollMaxY() Get max scroll Y')
	_Write_CallTip("_ImGui_SetScrollX", 				'_ImGui_SetScrollX($scroll_x) Set current scroll X')
	_Write_CallTip("_ImGui_SetScrollY", 				'_ImGui_SetScrollY($scroll_y) Set current scroll Y')
	_Write_CallTip("_ImGui_SetScrollHereX", 			'_ImGui_SetScrollHereX($center_x_ratio = 0.5) Scroll here X')
	_Write_CallTip("_ImGui_SetScrollHereY", 			'_ImGui_SetScrollHereY($center_y_ratio = 0.5) Scroll here Y')
	_Write_CallTip("_ImGui_SetScrollFromPosX", 			'_ImGui_SetScrollFromPosX($local_x, $center_x_ratio = 0.5) ')
	_Write_CallTip("_ImGui_SetScrollFromPosY", 			'_ImGui_SetScrollFromPosY($local_y, $center_y_ratio = 0.5) ')
	_Write_CallTip("_ImGui_PushFont", 					'_ImGui_PushFont($font) Push font for the next drawings, must use with _ImGui_PopFont')
	_Write_CallTip("_ImGui_PopFont", 					'_ImGui_PopFont() ')
	_Write_CallTip("_ImGui_PushStyleColor", 			'_ImGui_PushStyleColor($idx, $col) Must use with _ImGui_PopStyleColor')
	_Write_CallTip("_ImGui_PopStyleColor", 				'_ImGui_PopStyleColor($count = 1) ')
	_Write_CallTip("_ImGui_PushStyleVar", 				'_ImGui_PushStyleVar($idx, $val) Must use with _ImGui_PopStyleVar')
	_Write_CallTip("_ImGui_PushStyleVarPos", 			'_ImGui_PushStyleVarPos($idx, $val_x, $val_y) Must use with _ImGui_PopStyleVar')
	_Write_CallTip("_ImGui_PopStyleVar", 				'_ImGui_PopStyleVar($count = 1) ')
	_Write_CallTip("_ImGui_GetFont", 					'_ImGui_GetFont() Get the current font handle')
	_Write_CallTip("_ImGui_GetFontSize", 				'_ImGui_GetFontSize() ')
	_Write_CallTip("_ImGui_GetFontTexUvWhitePixel", 	'_ImGui_GetFontTexUvWhitePixel() ')
	_Write_CallTip("_ImGui_GetColorU32", 				'_ImGui_GetColorU32($idx, $alpha_mul = 1) ')
	_Write_CallTip("_ImGui_PushItemWidth", 				'_ImGui_PushItemWidth($item_width) Must use with _ImGui_PopItemWidth')
	_Write_CallTip("_ImGui_PopItemWidth", 				'_ImGui_PopItemWidth() ')
	_Write_CallTip("_ImGui_SetNextItemWidth", 			'_ImGui_SetNextItemWidth($item_width) ')
	_Write_CallTip("_ImGui_CalcItemWidth", 				'_ImGui_CalcItemWidth() ')
	_Write_CallTip("_ImGui_PushTextWrapPos", 			'_ImGui_PushTextWrapPos($wrap_pos_x = 0) Must use with _ImGui_PopTextWrapPos')
	_Write_CallTip("_ImGui_PopTextWrapPos", 			'_ImGui_PopTextWrapPos() ')
	_Write_CallTip("_ImGui_PushAllowKeyboardFocus", 	'_ImGui_PushAllowKeyboardFocus($allow_keyboard_focus) Must use with _ImGui_PopTextWrapPos')
	_Write_CallTip("_ImGui_PopAllowKeyboardFocus", 		'_ImGui_PopAllowKeyboardFocus() ')
	_Write_CallTip("_ImGui_PushButtonRepeat", 			'_ImGui_PushButtonRepeat($repeat) Must use with _ImGui_PopButtonRepeat')
	_Write_CallTip("_ImGui_PopButtonRepeat", 			'_ImGui_PopButtonRepeat() ')
	_Write_CallTip("_ImGui_Separator", 					'_ImGui_Separator() ')
	_Write_CallTip("_ImGui_SameLine", 					'_ImGui_SameLine($offset_from_start_x = 0, $spacing_w = -1) ')
	_Write_CallTip("_ImGui_NewLine", 					'_ImGui_NewLine() ')
	_Write_CallTip("_ImGui_Spacing", 					'_ImGui_Spacing() ')
	_Write_CallTip("_ImGui_Dummy", 						'_ImGui_Dummy($size_x, $size_y) ')
	_Write_CallTip("_ImGui_Indent", 					'_ImGui_Indent($indent_w = 0) ')
	_Write_CallTip("_ImGui_Unindent", 					'_ImGui_Unindent($indent_w = 0) ')
	_Write_CallTip("_ImGui_BeginGroup", 				'_ImGui_BeginGroup() Create a group inside the window')
	_Write_CallTip("_ImGui_EndGroup", 					'_ImGui_EndGroup() ')
	_Write_CallTip("_ImGui_GetCursorPosX", 				'_ImGui_GetCursorPosX() ')
	_Write_CallTip("_ImGui_GetCursorPosY", 				'_ImGui_GetCursorPosY() ')
	_Write_CallTip("_ImGui_SetCursorPosX", 				'_ImGui_SetCursorPosX($x) ')
	_Write_CallTip("_ImGui_SetCursorPosY", 				'_ImGui_SetCursorPosY($y) ')
	_Write_CallTip("_ImGui_GetCursorPos", 				'_ImGui_GetCursorPos() ')
	_Write_CallTip("_ImGui_SetCursorPos", 				'_ImGui_SetCursorPos($local_pos_x, $local_pos_y) ')
	_Write_CallTip("_ImGui_GetCursorStartPos", 			'_ImGui_GetCursorStartPos() ')
	_Write_CallTip("_ImGui_GetCursorScreenPos", 		'_ImGui_GetCursorScreenPos() ')
	_Write_CallTip("_ImGui_SetCursorScreenPos", 		'_ImGui_SetCursorScreenPos($pos_x, $pos_y) ')
	_Write_CallTip("_ImGui_AlignTextToFramePadding", 	'_ImGui_AlignTextToFramePadding() ')
	_Write_CallTip("_ImGui_GetTextLineHeight", 				'_ImGui_GetTextLineHeight() ')
	_Write_CallTip("_ImGui_GetTextLineHeightWithSpacing", 	'_ImGui_GetTextLineHeightWithSpacing() ')
	_Write_CallTip("_ImGui_GetFrameHeight", 				'_ImGui_GetFrameHeight() ')
	_Write_CallTip("_ImGui_GetFrameHeightWithSpacing", 	'_ImGui_GetFrameHeightWithSpacing() ')
	_Write_CallTip("_ImGui_PushID", 					'_ImGui_PushID($str_id) ')
	_Write_CallTip("_ImGui_PopID", 						'_ImGui_PopID() ')
	_Write_CallTip("_ImGui_GetID", 						'_ImGui_GetID($str_id) ')
	_Write_CallTip("_ImGui_TextColored", 				'_ImGui_TextColored($text, $color = 0xFFFFFFFF) Add colored text')
	_Write_CallTip("_ImGui_TextDisabled", 				'_ImGui_TextDisabled($text) Add disabled text')
	_Write_CallTip("_ImGui_TextWrapped", 				'_ImGui_TextWrapped($text) Add wrapped text')
	_Write_CallTip("_ImGui_LabelText", 					'_ImGui_LabelText($label, $text) Add text with a label')
	_Write_CallTip("_ImGui_BulletText", 				'_ImGui_BulletText($text) ')
	_Write_CallTip("_ImGui_SmallButton", 				'_ImGui_SmallButton($label) ')
	_Write_CallTip("_ImGui_InvisibleButton", 			'_ImGui_InvisibleButton($str_id, $size_x, $size_y) ')
	_Write_CallTip("_ImGui_ArrowButton", 				'_ImGui_ArrowButton($str_id, $dir = $ImGuiDir_Up) ')
	_Write_CallTip("_ImGui_Image", 						'_ImGui_Image($user_texture_id, $size_x, $size_y, $uv0_x = 0, $uv0_y = 0, $uv1_x = 1, $uv1_y = 1, $tint_col = 0xFFFFFFFF, $border_col = 0) $user_texture_id: A handle returned from _ImGui_ImageFrom')
	_Write_CallTip("_ImGui_ImageButton", 				'_ImGui_ImageButton($user_texture_id, $size_x, $size_y, $uv0_x = 0, $uv0_y = 0, $uv1_x = 1, $uv1_y = 1, $frame_padding = -1, $bg_col = 0, $tint_col = 0xFFFFFFFF) $user_texture_id: A handle returned from _ImGui_ImageFrom')
	_Write_CallTip("_ImGui_CheckboxFlags", 				'_ImGui_CheckboxFlags($label, ByRef $flags, $flags_value) ')
	_Write_CallTip("_ImGui_RadioButton", 				'_ImGui_RadioButton($label, ByRef $v, $v_button) ')
	_Write_CallTip("_ImGui_ProgressBar", 				'_ImGui_ProgressBar($fraction, $size_arg_x = -1, $size_arg_y = 0, $overlay = "") ')
	_Write_CallTip("_ImGui_Bullet", 					'_ImGui_Bullet() ')
	_Write_CallTip("_ImGui_BeginCombo", 				'_ImGui_BeginCombo($label, $preview_value, $flags = $ImGuiComboFlags_None) ')
	_Write_CallTip("_ImGui_EndCombo", 					'_ImGui_EndCombo() ')
	_Write_CallTip("_ImGui_GetIO", 						'_ImGui_GetIO() ImGuiIO contains ImGui configurations')
	_Write_CallTip("_ImGui_GetStyle", 					'_ImGui_GetStyle() ImGuiStyle contains ImGui color and style settings')
	_Write_CallTip("_ImGui_SetStyleColor", 				'_ImGui_SetStyleColor($index, $color = 0xFFFFFFFF) ')
	_Write_CallTip("_ImGui_Selectable", 				'_ImGui_Selectable($label, $selected = False, $flags = $ImGuiSelectableFlags_None, $size_arg_x = 0, $size_arg_y = 0) ')
	_Write_CallTip("_ImGui_Columns", 					'_ImGui_Columns($columns_count = 1, $id = "", $border = true) ')
	_Write_CallTip("_ImGui_NextColumn", 				'_ImGui_NextColumn() ')
	_Write_CallTip("_ImGui_GetColumnIndex", 			'_ImGui_GetColumnIndex() ')
	_Write_CallTip("_ImGui_GetColumnWidth", 			'_ImGui_GetColumnWidth($column_index = -1) ')
	_Write_CallTip("_ImGui_SetColumnWidth", 			'_ImGui_SetColumnWidth($column_index, $width) ')
	_Write_CallTip("_ImGui_GetColumnOffset", 			'_ImGui_GetColumnOffset($column_index = -1) ')
	_Write_CallTip("_ImGui_SetColumnOffset", 			'_ImGui_SetColumnOffset($column_index, $offset) ')
	_Write_CallTip("_ImGui_GetColumnsCount", 			'_ImGui_GetColumnsCount() ')
	_Write_CallTip("_ImGui_DragFloat", 					'_ImGui_DragFloat($label, ByRef $v, $v_speed = 1, $v_min = 0, $v_max = 0, $format = "%3.f", $power = 1) ')
	_Write_CallTip("_ImGui_DragFloat2", 				'_ImGui_DragFloat2($label, ByRef $v, $v_speed = 1, $v_min = 0, $v_max = 0, $format = "%.3f", $power = 1) ')
	_Write_CallTip("_ImGui_DragFloat3", 				'_ImGui_DragFloat3($label, ByRef $v, $v_speed = 1, $v_min = 0, $v_max = 0, $format = "%.3f", $power = 1) ')
	_Write_CallTip("_ImGui_DragFloat4", 				'_ImGui_DragFloat4($label, ByRef $v, $v_speed = 1, $v_min = 0, $v_max = 0, $format = "%.3f", $power = 1) ')
	_Write_CallTip("_ImGui_DragFloatRange2", 			'_ImGui_DragFloatRange2($label, ByRef $v_current_min, ByRef $v_current_max, $v_speed = 1, $v_min = 0, $v_max = 0, $format = "%.3f", $format_max = "", $power = 1) ')
	_Write_CallTip("_ImGui_DragInt", 					'_ImGui_DragInt($label, ByRef $v, $v_speed = 1, $v_min = 0, $v_max = 0, $format = "%d") ')
	_Write_CallTip("_ImGui_DragInt2", 					'_ImGui_DragInt2($label, ByRef $v, $v_speed = 1, $v_min = 0, $v_max = 0, $format ="%d") ')
	_Write_CallTip("_ImGui_DragInt3", 					'_ImGui_DragInt3($label, ByRef $v, $v_speed = 1, $v_min = 0, $v_max = 0, $format ="%d") ')
	_Write_CallTip("_ImGui_DragInt4", 					'_ImGui_DragInt4($label, ByRef $v, $v_speed = 1, $v_min = 0, $v_max = 0, $format ="%d") ')
	_Write_CallTip("_ImGui_DragIntRange2", 				'_ImGui_DragIntRange2($label, ByRef $v_current_min, ByRef $v_current_max, $v_speed = 1, $v_min = 0, $v_max = 0, $format = "%.3f", $format_max = "") ')
	_Write_CallTip("_ImGui_SliderFloat", 				'_ImGui_SliderFloat($text, ByRef $value, $v_min, $v_max, $format = "%.3f", $power = 1) Return true if being clicked on')
	_Write_CallTip("_ImGui_SliderFloat2", 				'_ImGui_SliderFloat2($label, ByRef $v, $v_min, $v_max, $format = "%.3f", $power = 1) ')
	_Write_CallTip("_ImGui_SliderFloat3", 				'_ImGui_SliderFloat3($label, ByRef $v, $v_min, $v_max, $format = "%.3f", $power = 1) ')
	_Write_CallTip("_ImGui_SliderFloat4", 				'_ImGui_SliderFloat4($label, ByRef $v, $v_min, $v_max, $format = "%.3f", $power = 1) ')
	_Write_CallTip("_ImGui_SliderAngle", 				'_ImGui_SliderAngle($label, ByRef $v_rad, $v_degrees_min = -360, $v_degrees_max = 360, $format = "%.0f deg") ')
	_Write_CallTip("_ImGui_SliderInt", 					'_ImGui_SliderInt($label, ByRef $v, $v_min, $v_max, $format = "%d") ')
	_Write_CallTip("_ImGui_SliderInt2", 				'_ImGui_SliderInt2($label, ByRef $v, $v_min, $v_max, $format = "%d") ')
	_Write_CallTip("_ImGui_SliderInt3", 				'_ImGui_SliderInt3($label, ByRef $v, $v_min, $v_max, $format = "%d") ')
	_Write_CallTip("_ImGui_SliderInt4", 				'_ImGui_SliderInt4($label, ByRef $v, $v_min, $v_max, $format = "%d") ')
	_Write_CallTip("_ImGui_VSliderInt", 				'_ImGui_VSliderInt($label, $size_x, $size_y, ByRef $v, $v_min, $v_max, $format = "%d") ')
	_Write_CallTip("_ImGui_VSliderFloat", 				'_ImGui_VSliderFloat($label, $size_x, $size_y, ByRef $v, $v_min, $v_max, $format = "%.3f", $power = 1) ')
	_Write_CallTip("_ImGui_InputFloat", 				'_ImGui_InputFloat($label, ByRef $v, $step = 0, $step_fast = 0, $format = "%.3f", $flags = $ImGuiInputTextFlags_None) ')
	_Write_CallTip("_ImGui_InputFloat2", 				'_ImGui_InputFloat2($label, ByRef $v, $format = "%.3f", $flags = $ImGuiInputTextFlags_None) ')
	_Write_CallTip("_ImGui_InputFloat3", 				'_ImGui_InputFloat3($label, ByRef $v, $format = "%.3f", $flags = $ImGuiInputTextFlags_None) ')
	_Write_CallTip("_ImGui_InputFloat4", 				'_ImGui_InputFloat4($label, ByRef $v, $format = "%.3f", $flags = $ImGuiInputTextFlags_None) ')
	_Write_CallTip("_ImGui_InputInt", 					'_ImGui_InputInt($label, ByRef $v, $step = 1, $step_fast = 100, $flags = $ImGuiInputTextFlags_None) ')
	_Write_CallTip("_ImGui_InputInt2", 					'_ImGui_InputInt2($label, ByRef $v, $flags = $ImGuiInputTextFlags_None) ')
	_Write_CallTip("_ImGui_InputInt3", 					'_ImGui_InputInt3($label, ByRef $v, $flags = $ImGuiInputTextFlags_None) ')
	_Write_CallTip("_ImGui_InputInt4", 					'_ImGui_InputInt4($label, ByRef $v, $flags = $ImGuiInputTextFlags_None) ')
	_Write_CallTip("_ImGui_InputDouble", 				'_ImGui_InputDouble($label, ByRef $v, $step = 0, $step_fast = 0, $format = "%.6f", $flags = $ImGuiInputTextFlags_None) ')
	_Write_CallTip("_ImGui_ColorEdit", 					'_ImGui_ColorEdit($label, ByRef $color, $flags = $ImGuiColorEditFlags_None) ')
	_Write_CallTip("_ImGui_ColorPicker", 				'_ImGui_ColorPicker($label, ByRef $color, $flags = $ImGuiColorEditFlags_None) ')
	_Write_CallTip("_ImGui_TreeNode", 					'_ImGui_TreeNode($label) ')
	_Write_CallTip("_ImGui_TreeNodeEx", 				'_ImGui_TreeNodeEx($label, $flags = $ImGuiTreeNodeFlags_None) ')
	_Write_CallTip("_ImGui_TreePush", 					'_ImGui_TreePush($str_id) ')
	_Write_CallTip("_ImGui_TreePop", 					'_ImGui_TreePop() ')
	_Write_CallTip("_ImGui_GetTreeNodeToLabelSpacing", 	'_ImGui_GetTreeNodeToLabelSpacing() ')
	_Write_CallTip("_ImGui_CollapsingHeader", 			'_ImGui_CollapsingHeader($label, $flags = $ImGuiTreeNodeFlags_None) ')
	_Write_CallTip("_ImGui_CollapsingHeaderEx", 		'_ImGui_CollapsingHeaderEx($label, ByRef $p_open, $flags = $ImGuiTreeNodeFlags_None) ')
	_Write_CallTip("_ImGui_SetNextItemOpen", 			'_ImGui_SetNextItemOpen($is_open, $cond = $ImGuiCond_None) ')
	_Write_CallTip("_ImGui_ListBox", 					'_ImGui_ListBox($label, ByRef $current_item, $items, $height_items = -1) ')
	_Write_CallTip("_ImGui_ListBoxHeader", 				'_ImGui_ListBoxHeader($label, $size_arg_x = 0, $size_arg_y = 0) ')
	_Write_CallTip("_ImGui_ListBoxHeaderEx", 			'_ImGui_ListBoxHeaderEx($label, $items_count, $height_in_items = -1) ')
	_Write_CallTip("_ImGui_ListBoxFooter", 				'_ImGui_ListBoxFooter() ')
	_Write_CallTip("_ImGui_PlotLines", 					'_ImGui_PlotLines($label, $values, $values_offset = 0, $overlay_text = "", $scale_min = $FLT_MAX, $scale_max = $FLT_MAX, $graph_size_x = 0, $graph_size_y = 0, $stride = 4) ')
	_Write_CallTip("_ImGui_PlotHistogram", 				'_ImGui_PlotHistogram($label, $values, $values_offset = 0, $overlay_text = "", $scale_min = $FLT_MAX, $scale_max = $FLT_MAX, $graph_size_x = 0, $graph_size_y = 0, $stride = 4) ')
	_Write_CallTip("_ImGui_ValueBool", 					'_ImGui_ValueBool($prefix, $b) ')
	_Write_CallTip("_ImGui_ValueInt", 					'_ImGui_ValueInt($prefix, $v) ')
	_Write_CallTip("_ImGui_ValueFloat", 				'_ImGui_ValueFloat($prefix, $v, $float_format = "") ')
	_Write_CallTip("_ImGui_BeginMenuBar", 				'_ImGui_BeginMenuBar() ')
	_Write_CallTip("_ImGui_EndMenuBar", 				'_ImGui_EndMenuBar() ')
	_Write_CallTip("_ImGui_BeginMainMenuBar", 			'_ImGui_BeginMainMenuBar() ')
	_Write_CallTip("_ImGui_EndMainMenuBar", 			'_ImGui_EndMainMenuBar() ')
	_Write_CallTip("_ImGui_BeginMenu", 					'_ImGui_BeginMenu($label, $enabled = True) ')
	_Write_CallTip("_ImGui_EndMenu", 					'_ImGui_EndMenu() ')
	_Write_CallTip("_ImGui_MenuItem", 					'_ImGui_MenuItem($label, $shortcut = "", $selected = False, $enabled = True) ')
	_Write_CallTip("_ImGui_MenuItemEx", 				'_ImGui_MenuItemEx($label, $shortcut, ByRef $p_selected, $enabled = True) ')
	_Write_CallTip("_ImGui_ShowDemoWindow", 			'_ImGui_ShowDemoWindow() ')
	_Write_CallTip("_ImGui_ToolTip", 					'_ImGui_ToolTip($text) ')
	_Write_CallTip("_ImGui_BeginTooltip", 				'_ImGui_BeginTooltip() ')
	_Write_CallTip("_ImGui_EndTooltip", 				'_ImGui_EndTooltip() ')
	_Write_CallTip("_ImGui_SetTooltip", 				'_ImGui_SetTooltip($text) ')
	_Write_CallTip("_ImGui_BeginPopup", 				'_ImGui_BeginPopup($str_id, $flags = $ImGuiWindowFlags_None) ')
	_Write_CallTip("_ImGui_BeginPopupModal", 			'_ImGui_BeginPopupModal($name, $flags = $ImGuiWindowFlags_None) ')
	_Write_CallTip("_ImGui_BeginPopupModalEx", 			'_ImGui_BeginPopupModalEx($name, ByRef $p_open, $flags = $ImGuiWindowFlags_None) ')
	_Write_CallTip("_ImGui_EndPopup", 					'_ImGui_EndPopup() ')
	_Write_CallTip("_ImGui_OpenPopup", 					'_ImGui_OpenPopup($str_id, $popup_flags = $ImGuiPopupFlags_MouseButtonLeft) ')
	_Write_CallTip("_ImGui_OpenPopupContextItem", 		'_ImGui_OpenPopupContextItem($str_id = "", $popup_flags = $ImGuiPopupFlags_MouseButtonLeft) ')
	_Write_CallTip("_ImGui_CloseCurrentPopup", 			'_ImGui_CloseCurrentPopup() ')
	_Write_CallTip("_ImGui_BeginPopupContextItem", 		'_ImGui_BeginPopupContextItem($str_id = "", $popup_flags = $ImGuiPopupFlags_MouseButtonLeft) ')
	_Write_CallTip("_ImGui_BeginPopupContextWindow", 	'_ImGui_BeginPopupContextWindow($str_id = "", $popup_flags = $ImGuiPopupFlags_MouseButtonLeft) ')
	_Write_CallTip("_ImGui_BeginPopupContextVoid", 		'_ImGui_BeginPopupContextVoid($str_id = "", $popup_flags = $ImGuiPopupFlags_MouseButtonLeft) ')
	_Write_CallTip("_ImGui_IsPopupOpen", 				'_ImGui_IsPopupOpen($str_id, $popup_flags = $ImGuiPopupFlags_None) ')
	_Write_CallTip("_ImGui_BeginTabBar", 				'_ImGui_BeginTabBar($str_id, $flags = $ImGuiTabBarFlags_None) ')
	_Write_CallTip("_ImGui_EndTabBar", 					'_ImGui_EndTabBar() ')
	_Write_CallTip("_ImGui_BeginTabItemEx", 			'_ImGui_BeginTabItemEx($label, ByRef $p_open, $flags = $ImGuiTabItemFlags_None) ')
	_Write_CallTip("_ImGui_BeginTabItem", 				'_ImGui_BeginTabItem($label, $flags = $ImGuiTabItemFlags_None) ')
	_Write_CallTip("_ImGui_EndTabItem", 				'_ImGui_EndTabItem() ')
	_Write_CallTip("_ImGui_SetTabItemClosed", 			'_ImGui_SetTabItemClosed($label) ')
	_Write_CallTip("_ImGui_DockSpace", 					'_ImGui_DockSpace($id, $size_arg_x = 0, $size_arg_y = 0, $flags = $ImGuiDockNodeFlags_None) ')
	_Write_CallTip("_ImGui_DockSpaceOverViewport", 		'_ImGui_DockSpaceOverViewport($viewport = 0, $dockspace_flags = $ImGuiDockNodeFlags_None) ')
	_Write_CallTip("_ImGui_SetNextWindowDockID", 		'_ImGui_SetNextWindowDockID($id, $cond = $ImGuiCond_None) ')
	_Write_CallTip("_ImGui_SetNextWindowClass", 		'_ImGui_SetNextWindowClass($window_class) ')
	_Write_CallTip("_ImGui_GetWindowDockID", 			'_ImGui_GetWindowDockID() ')
	_Write_CallTip("_ImGui_IsWindowDocked", 			'_ImGui_IsWindowDocked() ')
	_Write_CallTip("_ImGui_BeginDragDropSource", 		'_ImGui_BeginDragDropSource($flags = $ImGuiDragDropFlags_None) ')
	_Write_CallTip("_ImGui_PushClipRect", 				'_ImGui_PushClipRect($clip_rect_min_x, $clip_rect_min_y, $clip_rect_max_x, $clip_rect_max_y, $intersect_with_current_clip_rect) ')
	_Write_CallTip("_ImGui_PopClipRect", 				'_ImGui_PopClipRect() ')
	_Write_CallTip("_ImGui_SetItemDefaultFocus", 		'_ImGui_SetItemDefaultFocus() ')
	_Write_CallTip("_ImGui_SetKeyboardFocusHere", 		'_ImGui_SetKeyboardFocusHere($offset = 0) ')
	_Write_CallTip("_ImGui_IsItemHovered", 				'_ImGui_IsItemHovered($flags = $ImGuiHoveredFlags_None) ')
	_Write_CallTip("_ImGui_IsItemActive", 				'_ImGui_IsItemActive() ')
	_Write_CallTip("_ImGui_IsItemFocused", 				'_ImGui_IsItemFocused() ')
	_Write_CallTip("_ImGui_IsItemVisible", 				'_ImGui_IsItemVisible() ')
	_Write_CallTip("_ImGui_IsItemEdited", 				'_ImGui_IsItemEdited() ')
	_Write_CallTip("_ImGui_IsItemActivated", 			'_ImGui_IsItemActivated() ')
	_Write_CallTip("_ImGui_IsItemDeactivated", 			'_ImGui_IsItemDeactivated() ')
	_Write_CallTip("_ImGui_IsItemDeactivatedAfterEdit", '_ImGui_IsItemDeactivatedAfterEdit() ')
	_Write_CallTip("_ImGui_IsItemToggledOpen", 			'_ImGui_IsItemToggledOpen() ')
	_Write_CallTip("_ImGui_IsAnyItemHovered", 			'_ImGui_IsAnyItemHovered() ')
	_Write_CallTip("_ImGui_IsAnyItemActive",			'_ImGui_IsAnyItemActive() ')
	_Write_CallTip("_ImGui_IsAnyItemFocused", 			'_ImGui_IsAnyItemFocused() ')
	_Write_CallTip("_ImGui_SetItemAllowOverlap", 		'_ImGui_SetItemAllowOverlap() ')
	_Write_CallTip("_ImGui_IsItemClicked", 				'_ImGui_IsItemClicked($mouse_button = $ImGuiMouseButton_Left) ')
	_Write_CallTip("_ImGui_IsRectVisible", 				'_ImGui_IsRectVisible($size_x, $size_y) ')
	_Write_CallTip("_ImGui_IsRectVisibleEx", 			'_ImGui_IsRectVisibleEx($rect_min_x, $rect_min_y, $rect_max_x, $rect_max_y) ')
	_Write_CallTip("_ImGui_GetTime", 					'_ImGui_GetTime() ')
	_Write_CallTip("_ImGui_GetFrameCount", 				'_ImGui_GetFrameCount() ')
	_Write_CallTip("_ImGui_BeginChildFrame", 			'_ImGui_BeginChildFrame($id, $size_x, $size_y, $extra_flags = $ImGuiWindowFlags_None) ')
	_Write_CallTip("_ImGui_EndChildFrame", 				'_ImGui_EndChildFrame() ')
	_Write_CallTip("_ImGui_CalcTextSize", 				'_ImGui_CalcTextSize($text, $hide_text_after_double_hash = false, $wrap_width = -1) Calculate text size on screen, return [x, y]')
	_Write_CallTip("_ImGui_GetKeyIndex", 				'_ImGui_GetKeyIndex($imgui_key) ')
	_Write_CallTip("_ImGui_IsKeyDown", 					'_ImGui_IsKeyDown($user_key_index) ')
	_Write_CallTip("_ImGui_IsKeyPressed", 				'_ImGui_IsKeyPressed($user_key_index, $repeat = true) ')
	_Write_CallTip("_ImGui_IsKeyReleased", 				'_ImGui_IsKeyReleased($user_key_index) ')
	_Write_CallTip("_ImGui_GetKeyPressedAmount", 		'_ImGui_GetKeyPressedAmount($key_index, $repeat_delay, $repeat_rate) ')
	_Write_CallTip("_ImGui_CaptureKeyboardFromApp", 	'_ImGui_CaptureKeyboardFromApp($capture) ')
	_Write_CallTip("_ImGui_IsMouseDown", 				'_ImGui_IsMouseDown($button = $ImGuiMouseButton_Left) ')
	_Write_CallTip("_ImGui_IsMouseClicked", 			'_ImGui_IsMouseClicked($button = $ImGuiMouseButton_Left, $repeat = False) ')
	_Write_CallTip("_ImGui_IsMouseReleased", 			'_ImGui_IsMouseReleased($button = $ImGuiMouseButton_Left) ')
	_Write_CallTip("_ImGui_IsMouseHoveringRect", 		'_ImGui_IsMouseHoveringRect($r_min_x, $r_min_y, $r_max_x, $r_max_y, $clip = True) ')
	_Write_CallTip("_ImGui_IsMousePosValid", 			'_ImGui_IsMousePosValid() ')
	_Write_CallTip("_ImGui_IsAnyMouseDown", 			'_ImGui_IsAnyMouseDown() ')
	_Write_CallTip("_ImGui_IsMouseDragging", 			'_ImGui_IsMouseDragging($button = $ImGuiMouseButton_Left, $lock_threshold = -1) ')
	_Write_CallTip("_ImGui_ResetMouseDragDelta", 		'_ImGui_ResetMouseDragDelta($button = $ImGuiMouseButton_Left) ')
	_Write_CallTip("_ImGui_GetMouseCursor", 			'_ImGui_GetMouseCursor() ')
	_Write_CallTip("_ImGui_SetMouseCursor", 			'_ImGui_SetMouseCursor($cursor_type = $ImGuiMouseCursor_Arrow) ')
	_Write_CallTip("_ImGui_CaptureMouseFromApp", 		'_ImGui_CaptureMouseFromApp($capture) ')
	_Write_CallTip("_ImGui_LoadIniSettingsFromDisk", 	'_ImGui_LoadIniSettingsFromDisk($ini_filename) ')
	_Write_CallTip("_ImGui_SaveIniSettingsToDisk", 		'_ImGui_SaveIniSettingsToDisk($ini_filename) ')
	_Write_CallTip("_ImGui_GetMainViewport", 			'_ImGui_GetMainViewport() ')
	_Write_CallTip("_ImGui_UpdatePlatformWindows", 			'_ImGui_UpdatePlatformWindows() ')
	_Write_CallTip("_ImGui_RenderPlatformWindowsDefault", 	'_ImGui_RenderPlatformWindowsDefault($platform_render_arg, $renderer_render_arg) ')
	_Write_CallTip("_ImGui_DestroyPlatformWindows", 		'_ImGui_DestroyPlatformWindows() ')

	_Write_CallTip("_ImDraw_SetDrawList", 				'_ImDraw_SetDrawList($draw_list) Set draw list for drawing functions')
	_Write_CallTip("_ImDraw_SetOffset", 				'_ImDraw_SetOffset($x, $y) Set draw offset')
	_Write_CallTip("_ImDraw_GetDrawList", 				'_ImDraw_GetDrawList() Get the current draw list')
	_Write_CallTip("_ImDraw_AddLine", 					'_ImDraw_AddLine($p1_x, $p1_y, $p2_x, $p2_y, $col = 0xFFFFFFFF, $thickness = 1) ')
	_Write_CallTip("_ImDraw_AddRect", 					'_ImDraw_AddRect($x, $y, $w, $h, $col = 0xFFFFFFFF, $rounding = 0, $rounding_corners = $ImDrawCornerFlags_None, $thickness = 1) ')
	_Write_CallTip("_ImDraw_AddRectFilled", 			'_ImDraw_AddRectFilled( $x, $y, $w, $h, $col = 0xFFFFFFFF, $rounding = 0, $rounding_corners = $ImDrawCornerFlags_None) ')
	_Write_CallTip("_ImDraw_AddRectFilledMultiColor", 	'_ImDraw_AddRectFilledMultiColor($p_min_x, $p_min_y, $p_max_x, $p_max_y, $col_upr_left, $col_upr_right, $col_bot_right, $col_bot_left) ')
	_Write_CallTip("_ImDraw_AddQuad", 					'_ImDraw_AddQuad($p1_x, $p1_y, $p2_x, $p2_y, $p3_x, $p3_y, $p4_x, $p4_y, $col = 0xFFFFFFFF, $thickness = 1) ')
	_Write_CallTip("_ImDraw_AddQuadFilled", 			'_ImDraw_AddQuadFilled($p1_x, $p1_y, $p2_x, $p2_y, $p3_x, $p3_y, $p4_x, $p4_y, $col = 0xFFFFFFFF) ')
	_Write_CallTip("_ImDraw_AddTriangle", 				'_ImDraw_AddTriangle($p1_x, $p1_y, $p2_x, $p2_y, $p3_x, $p3_y, $col = 0xFFFFFFFF, $thickness = 1) ')
	_Write_CallTip("_ImDraw_AddTriangleFilled", 		'_ImDraw_AddTriangleFilled($p1_x, $p1_y, $p2_x, $p2_y, $p3_x, $p3_y, $col = 0xFFFFFFFF) ')
	_Write_CallTip("_ImDraw_AddCircle", 				'_ImDraw_AddCircle($center_x, $center_y, $radius, $col = 0xFFFFFFFF, $num_segments = 30, $thickness = 1) ')
	_Write_CallTip("_ImDraw_AddCircleFilled", 			'_ImDraw_AddCircleFilled($center_x, $center_y, $radius, $col = 0xFFFFFFFF, $num_segments = $radius/3+10) ')
	_Write_CallTip("_ImDraw_AddNgon", 					'_ImDraw_AddNgon($center_x, $center_y, $radius, $col = 0xFFFFFFFF, $num_segments = 5, $thickness = 1) ')
	_Write_CallTip("_ImDraw_AddNgonFilled", 			'_ImDraw_AddNgonFilled($center_x, $center_y, $radius, $col = 0xFFFFFFFF, $num_segments = 5) ')
	_Write_CallTip("_ImDraw_AddText", 					'_ImDraw_AddText($text, $font, $font_size, $pos_x, $pos_y, $col = 0xFFFFFFFF, $wrap_width = 0) ')
	_Write_CallTip("_ImDraw_AddPolyline", 				'_ImDraw_AddPolyline($points, $col = 0xFFFFFFFF, $closed = True, $thickness = 1) ')
	_Write_CallTip("_ImDraw_AddConvexPolyFilled", 		'_ImDraw_AddConvexPolyFilled($points, $col = 0xFFFFFFFF) ')
	_Write_CallTip("_ImDraw_AddBezierCurve", 			'_ImDraw_AddBezierCurve($p1_x, $p1_y, $p2_x, $p2_y, $p3_x, $p3_y, $p4_x, $p4_y, $col = 0xFFFFFFFF, $thickness = 1, $num_segments = 30) ')

	_Write_CallTip("_ImDraw_AddImage", 					'_ImDraw_AddImage($user_texture_id, $p_min_x, $p_min_y, $p_max_x, $p_max_y, $uv_min_x = 0, $uv_min_y = 0, $uv_max_x = 1, $uv_max_y = 1, $col = 0xFFFFFFFF) ')
	_Write_CallTip("_ImDraw_AddImageQuad", 				'_ImDraw_AddImageQuad($user_texture_id, $p1_x, $p1_y, $p2_x, $p2_y, $p3_x, $p3_y, $p4_x, $p4_y, $uv1_x = 0, $uv1_y = 0, $uv2_x = 1, $uv2_y = 0, $uv3_x = 1, $uv3_y = 1, $uv4_x = 0, $uv4_y = 1, $col = 0xFFFFFFFF) ')
	_Write_CallTip("_ImDraw_AddImageRounded", 			'_ImDraw_AddImageRounded($user_texture_id, $p_min_x, $p_min_y, $p_max_x, $p_max_y, $uv_min_x = 0, $uv_min_y = 0, $uv_max_x = 1, $uv_max_y = 1, $col = 0xFFFFFFFF, $rounding = 5, $rounding_corners = $ImDrawCornerFlags_None) ')

	_Write_CallTip("_ImDraw_PathClear", 					'_ImDraw_PathClear() ')
	_Write_CallTip("_ImDraw_PathLineTo", 					'_ImDraw_PathLineTo($pos_x, $pos_y) ')
	_Write_CallTip("_ImDraw_PathLineToMergeDuplicate", 		'_ImDraw_PathLineToMergeDuplicate($pos_x, $pos_y) ')
	_Write_CallTip("_ImDraw_PathFillConvex", 				'_ImDraw_PathFillConvex($col) ')
	_Write_CallTip("_ImDraw_PathStroke", 					'_ImDraw_PathStroke($col, $closed, $thickness = 1) ')
	_Write_CallTip("_ImDraw_PathArcTo", 					'_ImDraw_PathArcTo($center_x, $center_y, $radius, $a_min, $a_max, $num_segments = 20) ')
	_Write_CallTip("_ImDraw_PathArcToFast", 				'_ImDraw_PathArcToFast($center_x, $center_y, $radius, $a_min_of_12, $a_max_of_12) ')
	_Write_CallTip("_ImDraw_PathRect", 						'_ImDraw_PathRect($rect_min_x, $rect_min_y, $rect_max_x, $rect_max_y, $rounding = 0, $rounding_corners = $ImDrawCornerFlags_All) ')
	_Write_CallTip("_ImDraw_PathBezierCurveTo", 			'_ImDraw_PathBezierCurveTo($p2_x, $p2_y, $p3_x, $p3_y, $p4_x, $p4_y, $num_segments = 0) ')

	_Write_CallTip("_ImDraw_AddImageFit", 					'_ImDraw_AddImageFit($user_texture_id, $pos_x, $pos_y, $size_x = 0, $size_y = 0, $crop_area = True, $rounding = 0, $tint_col = 0xFFFFFFFF, $rounding_corners = $ImDrawCornerFlags_All) ')
	_Write_CallTip("_ImGui_ImageFit", 						'_ImGui_ImageFit($user_texture_id, $size_x = 0, $size_y = 0, $crop_area = True, $rounding = 0, $tint_col = 0xFFFFFFFF, $rounding_corners = $ImDrawCornerFlags_All) ')
	_Write_CallTip("_ImGui_ImageFromFile", 					'_ImGui_ImageFromFile($file_path) ')
	_Write_CallTip("_ImGui_ImageFromURL", 					'_ImGui_ImageFromURL($url) ')
	_Write_CallTip("_ImGui_ImageGetSize", 					'_ImGui_ImageGetSize($user_texture_id) ')

	_Write_CallTip("_GetStructArrayValue", 				'_GetStructArrayValue($struct, $index, $index_array) Use to get data from ImGuiIO')
	_Write_CallTip("_SetStructArrayValue", 				'_SetStructArrayValue($struct, $index, $index_array, $value) Set ImGuiIO data')

	_Write_CallTip("$FLT_MAX", 												"$FLT_MAX")
	_Write_CallTip("$ImGuiWindowFlags_None", 								"$ImGuiWindowFlags_None")
	_Write_CallTip("$ImGuiWindowFlags_NoTitleBar", 							"$ImGuiWindowFlags_NoTitleBar")
	_Write_CallTip("$ImGuiWindowFlags_NoResize", 							"$ImGuiWindowFlags_NoResize")
	_Write_CallTip("$ImGuiWindowFlags_NoMove", 								"$ImGuiWindowFlags_NoMove")
	_Write_CallTip("$ImGuiWindowFlags_NoScrollbar", 						"$ImGuiWindowFlags_NoScrollbar")
	_Write_CallTip("$ImGuiWindowFlags_NoScrollWithMouse", 					"$ImGuiWindowFlags_NoScrollWithMouse")
	_Write_CallTip("$ImGuiWindowFlags_NoCollapse", 							"$ImGuiWindowFlags_NoCollapse")
	_Write_CallTip("$ImGuiWindowFlags_AlwaysAutoResize", 					"$ImGuiWindowFlags_AlwaysAutoResize")
	_Write_CallTip("$ImGuiWindowFlags_NoBackground", 						"$ImGuiWindowFlags_NoBackground")
	_Write_CallTip("$ImGuiWindowFlags_NoSavedSettings", 					"$ImGuiWindowFlags_NoSavedSettings")
	_Write_CallTip("$ImGuiWindowFlags_NoMouseInputs", 						"$ImGuiWindowFlags_NoMouseInputs")
	_Write_CallTip("$ImGuiWindowFlags_MenuBar", 							"$ImGuiWindowFlags_MenuBar")
	_Write_CallTip("$ImGuiWindowFlags_HorizontalScrollbar", 				"$ImGuiWindowFlags_HorizontalScrollbar")
	_Write_CallTip("$ImGuiWindowFlags_NoFocusOnAppearing", 					"$ImGuiWindowFlags_NoFocusOnAppearing")
	_Write_CallTip("$ImGuiWindowFlags_NoBringToFrontOnFocus", 				"$ImGuiWindowFlags_NoBringToFrontOnFocus")
	_Write_CallTip("$ImGuiWindowFlags_AlwaysVerticalScrollbar=", 			"$ImGuiWindowFlags_AlwaysVerticalScrollbar=")
	_Write_CallTip("$ImGuiWindowFlags_AlwaysHorizontalScrollbar=", 			"$ImGuiWindowFlags_AlwaysHorizontalScrollbar=")
	_Write_CallTip("$ImGuiWindowFlags_AlwaysUseWindowPadding", 				"$ImGuiWindowFlags_AlwaysUseWindowPadding")
	_Write_CallTip("$ImGuiWindowFlags_NoNavInputs", 						"$ImGuiWindowFlags_NoNavInputs")
	_Write_CallTip("$ImGuiWindowFlags_NoNavFocus", 							"$ImGuiWindowFlags_NoNavFocus")
	_Write_CallTip("$ImGuiWindowFlags_UnsavedDocument", 					"$ImGuiWindowFlags_UnsavedDocument")
	_Write_CallTip("$ImGuiWindowFlags_NoDocking", 							"$ImGuiWindowFlags_NoDocking")
	_Write_CallTip("$ImGuiWindowFlags_NoNav", 								"$ImGuiWindowFlags_NoNav")
	_Write_CallTip("$ImGuiWindowFlags_NoDecoration", 						"$ImGuiWindowFlags_NoDecoration")
	_Write_CallTip("$ImGuiWindowFlags_NoInputs", 							"$ImGuiWindowFlags_NoInputs")
	_Write_CallTip("$ImGuiWindowFlags_NavFlattened", 						"$ImGuiWindowFlags_NavFlattened")
	_Write_CallTip("$ImGuiWindowFlags_ChildWindow", 						"$ImGuiWindowFlags_ChildWindow")
	_Write_CallTip("$ImGuiWindowFlags_Tooltip", 							"$ImGuiWindowFlags_Tooltip")
	_Write_CallTip("$ImGuiWindowFlags_Popup", 								"$ImGuiWindowFlags_Popup")
	_Write_CallTip("$ImGuiWindowFlags_Modal", 								"$ImGuiWindowFlags_Modal")
	_Write_CallTip("$ImGuiWindowFlags_ChildMenu", 							"$ImGuiWindowFlags_ChildMenu")
	_Write_CallTip("$ImGuiWindowFlags_DockNodeHost", 						"$ImGuiWindowFlags_DockNodeHost")
	_Write_CallTip("$ImGuiInputTextFlags_None", 							"$ImGuiInputTextFlags_None")
	_Write_CallTip("$ImGuiInputTextFlags_CharsDecimal", 					"$ImGuiInputTextFlags_CharsDecimal")
	_Write_CallTip("$ImGuiInputTextFlags_CharsHexadecimal", 				"$ImGuiInputTextFlags_CharsHexadecimal")
	_Write_CallTip("$ImGuiInputTextFlags_CharsUppercase", 					"$ImGuiInputTextFlags_CharsUppercase")
	_Write_CallTip("$ImGuiInputTextFlags_CharsNoBlank", 					"$ImGuiInputTextFlags_CharsNoBlank")
	_Write_CallTip("$ImGuiInputTextFlags_AutoSelectAll", 					"$ImGuiInputTextFlags_AutoSelectAll")
	_Write_CallTip("$ImGuiInputTextFlags_EnterReturnsTrue", 				"$ImGuiInputTextFlags_EnterReturnsTrue")
	_Write_CallTip("$ImGuiInputTextFlags_CallbackCompletion", 				"$ImGuiInputTextFlags_CallbackCompletion")
	_Write_CallTip("$ImGuiInputTextFlags_CallbackHistory", 					"$ImGuiInputTextFlags_CallbackHistory")
	_Write_CallTip("$ImGuiInputTextFlags_CallbackAlways", 					"$ImGuiInputTextFlags_CallbackAlways")
	_Write_CallTip("$ImGuiInputTextFlags_CallbackCharFilter", 				"$ImGuiInputTextFlags_CallbackCharFilter")
	_Write_CallTip("$ImGuiInputTextFlags_AllowTabInput", 					"$ImGuiInputTextFlags_AllowTabInput")
	_Write_CallTip("$ImGuiInputTextFlags_CtrlEnterForNewLine", 				"$ImGuiInputTextFlags_CtrlEnterForNewLine")
	_Write_CallTip("$ImGuiInputTextFlags_NoHorizontalScroll", 				"$ImGuiInputTextFlags_NoHorizontalScroll")
	_Write_CallTip("$ImGuiInputTextFlags_AlwaysInsertMode", 				"$ImGuiInputTextFlags_AlwaysInsertMode")
	_Write_CallTip("$ImGuiInputTextFlags_ReadOnly", 						"$ImGuiInputTextFlags_ReadOnly")
	_Write_CallTip("$ImGuiInputTextFlags_Password", 						"$ImGuiInputTextFlags_Password")
	_Write_CallTip("$ImGuiInputTextFlags_NoUndoRedo", 						"$ImGuiInputTextFlags_NoUndoRedo")
	_Write_CallTip("$ImGuiInputTextFlags_CharsScientific", 					"$ImGuiInputTextFlags_CharsScientific")
	_Write_CallTip("$ImGuiInputTextFlags_CallbackResize", 					"$ImGuiInputTextFlags_CallbackResize")
	_Write_CallTip("$ImGuiInputTextFlags_Multiline", 						"$ImGuiInputTextFlags_Multiline")
	_Write_CallTip("$ImGuiInputTextFlags_NoMarkEdited", 					"$ImGuiInputTextFlags_NoMarkEdited")
	_Write_CallTip("$ImGuiTreeNodeFlags_None", 								"$ImGuiTreeNodeFlags_None")
	_Write_CallTip("$ImGuiTreeNodeFlags_Selected", 							"$ImGuiTreeNodeFlags_Selected")
	_Write_CallTip("$ImGuiTreeNodeFlags_Framed", 							"$ImGuiTreeNodeFlags_Framed")
	_Write_CallTip("$ImGuiTreeNodeFlags_AllowItemOverlap", 					"$ImGuiTreeNodeFlags_AllowItemOverlap")
	_Write_CallTip("$ImGuiTreeNodeFlags_NoTreePushOnOpen", 					"$ImGuiTreeNodeFlags_NoTreePushOnOpen")
	_Write_CallTip("$ImGuiTreeNodeFlags_NoAutoOpenOnLog", 					"$ImGuiTreeNodeFlags_NoAutoOpenOnLog")
	_Write_CallTip("$ImGuiTreeNodeFlags_DefaultOpen", 						"$ImGuiTreeNodeFlags_DefaultOpen")
	_Write_CallTip("$ImGuiTreeNodeFlags_OpenOnDoubleClick", 				"$ImGuiTreeNodeFlags_OpenOnDoubleClick")
	_Write_CallTip("$ImGuiTreeNodeFlags_OpenOnArrow", 						"$ImGuiTreeNodeFlags_OpenOnArrow")
	_Write_CallTip("$ImGuiTreeNodeFlags_Leaf", 								"$ImGuiTreeNodeFlags_Leaf")
	_Write_CallTip("$ImGuiTreeNodeFlags_Bullet", 							"$ImGuiTreeNodeFlags_Bullet")
	_Write_CallTip("$ImGuiTreeNodeFlags_FramePadding", 						"$ImGuiTreeNodeFlags_FramePadding")
	_Write_CallTip("$ImGuiTreeNodeFlags_SpanAvailWidth", 					"$ImGuiTreeNodeFlags_SpanAvailWidth")
	_Write_CallTip("$ImGuiTreeNodeFlags_SpanFullWidth", 					"$ImGuiTreeNodeFlags_SpanFullWidth")
	_Write_CallTip("$ImGuiTreeNodeFlags_NavLeftJumpsBackHere", 				"$ImGuiTreeNodeFlags_NavLeftJumpsBackHere")
	_Write_CallTip("$ImGuiTreeNodeFlags_CollapsingHeader", 					"$ImGuiTreeNodeFlags_CollapsingHeader")
	_Write_CallTip("$ImGuiPopupFlags_None", 								"$ImGuiPopupFlags_None")
	_Write_CallTip("$ImGuiPopupFlags_MouseButtonLeft", 						"$ImGuiPopupFlags_MouseButtonLeft")
	_Write_CallTip("$ImGuiPopupFlags_MouseButtonRight", 					"$ImGuiPopupFlags_MouseButtonRight")
	_Write_CallTip("$ImGuiPopupFlags_MouseButtonMiddle", 					"$ImGuiPopupFlags_MouseButtonMiddle")
	_Write_CallTip("$ImGuiPopupFlags_MouseButtonMask_", 					"$ImGuiPopupFlags_MouseButtonMask_")
	_Write_CallTip("$ImGuiPopupFlags_MouseButtonDefault_", 					"$ImGuiPopupFlags_MouseButtonDefault_")
	_Write_CallTip("$ImGuiPopupFlags_NoOpenOverExistingPopup", 				"$ImGuiPopupFlags_NoOpenOverExistingPopup")
	_Write_CallTip("$ImGuiPopupFlags_NoOpenOverItems", 						"$ImGuiPopupFlags_NoOpenOverItems")
	_Write_CallTip("$ImGuiPopupFlags_AnyPopupId", 							"$ImGuiPopupFlags_AnyPopupId")
	_Write_CallTip("$ImGuiPopupFlags_AnyPopupLevel", 						"$ImGuiPopupFlags_AnyPopupLevel")
	_Write_CallTip("$ImGuiPopupFlags_AnyPopup", 							"$ImGuiPopupFlags_AnyPopup")
	_Write_CallTip("$ImGuiSelectableFlags_None", 							"$ImGuiSelectableFlags_None")
	_Write_CallTip("$ImGuiSelectableFlags_DontClosePopups", 				"$ImGuiSelectableFlags_DontClosePopups")
	_Write_CallTip("$ImGuiSelectableFlags_SpanAllColumns", 					"$ImGuiSelectableFlags_SpanAllColumns")
	_Write_CallTip("$ImGuiSelectableFlags_AllowDoubleClick", 				"$ImGuiSelectableFlags_AllowDoubleClick")
	_Write_CallTip("$ImGuiSelectableFlags_Disabled", 						"$ImGuiSelectableFlags_Disabled")
	_Write_CallTip("$ImGuiSelectableFlags_AllowItemOverlap", 				"$ImGuiSelectableFlags_AllowItemOverlap")
	_Write_CallTip("$ImGuiComboFlags_None", 								"$ImGuiComboFlags_None")
	_Write_CallTip("$ImGuiComboFlags_PopupAlignLeft", 						"$ImGuiComboFlags_PopupAlignLeft")
	_Write_CallTip("$ImGuiComboFlags_HeightSmall", 							"$ImGuiComboFlags_HeightSmall")
	_Write_CallTip("$ImGuiComboFlags_HeightRegular", 						"$ImGuiComboFlags_HeightRegular")
	_Write_CallTip("$ImGuiComboFlags_HeightLarge", 							"$ImGuiComboFlags_HeightLarge")
	_Write_CallTip("$ImGuiComboFlags_HeightLargest", 						"$ImGuiComboFlags_HeightLargest")
	_Write_CallTip("$ImGuiComboFlags_NoArrowButton", 						"$ImGuiComboFlags_NoArrowButton")
	_Write_CallTip("$ImGuiComboFlags_NoPreview", 							"$ImGuiComboFlags_NoPreview")
	_Write_CallTip("$ImGuiComboFlags_HeightMask_", 							"$ImGuiComboFlags_HeightMask_")
	_Write_CallTip("$ImGuiTabBarFlags_None", 								"$ImGuiTabBarFlags_None")
	_Write_CallTip("$ImGuiTabBarFlags_Reorderable", 						"$ImGuiTabBarFlags_Reorderable")
	_Write_CallTip("$ImGuiTabBarFlags_AutoSelectNewTabs", 					"$ImGuiTabBarFlags_AutoSelectNewTabs")
	_Write_CallTip("$ImGuiTabBarFlags_TabListPopupButton", 					"$ImGuiTabBarFlags_TabListPopupButton")
	_Write_CallTip("$ImGuiTabBarFlags_NoCloseWithMiddleMouseButton", 		"$ImGuiTabBarFlags_NoCloseWithMiddleMouseButton")
	_Write_CallTip("$ImGuiTabBarFlags_NoTabListScrollingButtons", 			"$ImGuiTabBarFlags_NoTabListScrollingButtons")
	_Write_CallTip("$ImGuiTabBarFlags_NoTooltip", 							"$ImGuiTabBarFlags_NoTooltip")
	_Write_CallTip("$ImGuiTabBarFlags_FittingPolicyResizeDown", 			"$ImGuiTabBarFlags_FittingPolicyResizeDown")
	_Write_CallTip("$ImGuiTabBarFlags_FittingPolicyScroll", 				"$ImGuiTabBarFlags_FittingPolicyScroll")
	_Write_CallTip("$ImGuiTabBarFlags_FittingPolicyMask_", 					"$ImGuiTabBarFlags_FittingPolicyMask_")
	_Write_CallTip("$ImGuiTabBarFlags_FittingPolicyDefault_", 				"$ImGuiTabBarFlags_FittingPolicyDefault_")
	_Write_CallTip("$ImGuiTabItemFlags_None", 								"$ImGuiTabItemFlags_None")
	_Write_CallTip("$ImGuiTabItemFlags_UnsavedDocument", 					"$ImGuiTabItemFlags_UnsavedDocument")
	_Write_CallTip("$ImGuiTabItemFlags_SetSelected", 						"$ImGuiTabItemFlags_SetSelected")
	_Write_CallTip("$ImGuiTabItemFlags_NoCloseWithMiddleMouseButton", 		"$ImGuiTabItemFlags_NoCloseWithMiddleMouseButton")
	_Write_CallTip("$ImGuiTabItemFlags_NoPushId", 							"$ImGuiTabItemFlags_NoPushId")
	_Write_CallTip("$ImGuiTabItemFlags_NoTooltip", 							"$ImGuiTabItemFlags_NoTooltip")
	_Write_CallTip("$ImGuiFocusedFlags_None", 								"$ImGuiFocusedFlags_None")
	_Write_CallTip("$ImGuiFocusedFlags_ChildWindows", 						"$ImGuiFocusedFlags_ChildWindows")
	_Write_CallTip("$ImGuiFocusedFlags_RootWindow", 						"$ImGuiFocusedFlags_RootWindow")
	_Write_CallTip("$ImGuiFocusedFlags_AnyWindow", 							"$ImGuiFocusedFlags_AnyWindow")
	_Write_CallTip("$ImGuiFocusedFlags_RootAndChildWindows", 				"$ImGuiFocusedFlags_RootAndChildWindows")
	_Write_CallTip("$ImGuiHoveredFlags_None", 								"$ImGuiHoveredFlags_None")
	_Write_CallTip("$ImGuiHoveredFlags_ChildWindows", 						"$ImGuiHoveredFlags_ChildWindows")
	_Write_CallTip("$ImGuiHoveredFlags_RootWindow", 						"$ImGuiHoveredFlags_RootWindow")
	_Write_CallTip("$ImGuiHoveredFlags_AnyWindow", 							"$ImGuiHoveredFlags_AnyWindow")
	_Write_CallTip("$ImGuiHoveredFlags_AllowWhenBlockedByPopup", 			"$ImGuiHoveredFlags_AllowWhenBlockedByPopup")
	_Write_CallTip("$ImGuiHoveredFlags_AllowWhenBlockedByActiveItem", 		"$ImGuiHoveredFlags_AllowWhenBlockedByActiveItem")
	_Write_CallTip("$ImGuiHoveredFlags_AllowWhenOverlapped", 				"$ImGuiHoveredFlags_AllowWhenOverlapped")
	_Write_CallTip("$ImGuiHoveredFlags_AllowWhenDisabled", 					"$ImGuiHoveredFlags_AllowWhenDisabled")
	_Write_CallTip("$ImGuiHoveredFlags_RectOnly", 							"$ImGuiHoveredFlags_RectOnly")
	_Write_CallTip("$ImGuiHoveredFlags_RootAndChildWindows", 				"$ImGuiHoveredFlags_RootAndChildWindows")
	_Write_CallTip("$ImGuiDockNodeFlags_None", 								"$ImGuiDockNodeFlags_None")
	_Write_CallTip("$ImGuiDockNodeFlags_KeepAliveOnly", 					"$ImGuiDockNodeFlags_KeepAliveOnly")
	_Write_CallTip("$ImGuiDockNodeFlags_NoDockingInCentralNode", 			"$ImGuiDockNodeFlags_NoDockingInCentralNode")
	_Write_CallTip("$ImGuiDockNodeFlags_PassthruCentralNode", 				"$ImGuiDockNodeFlags_PassthruCentralNode")
	_Write_CallTip("$ImGuiDockNodeFlags_NoSplit", 							"$ImGuiDockNodeFlags_NoSplit")
	_Write_CallTip("$ImGuiDockNodeFlags_NoResize", 							"$ImGuiDockNodeFlags_NoResize")
	_Write_CallTip("$ImGuiDockNodeFlags_AutoHideTabBar", 					"$ImGuiDockNodeFlags_AutoHideTabBar")
	_Write_CallTip("$ImGuiDragDropFlags_None", 								"$ImGuiDragDropFlags_None")
	_Write_CallTip("$ImGuiDragDropFlags_SourceNoPreviewTooltip", 			"$ImGuiDragDropFlags_SourceNoPreviewTooltip")
	_Write_CallTip("$ImGuiDragDropFlags_SourceNoDisableHover", 				"$ImGuiDragDropFlags_SourceNoDisableHover")
	_Write_CallTip("$ImGuiDragDropFlags_SourceNoHoldToOpenOthers", 			"$ImGuiDragDropFlags_SourceNoHoldToOpenOthers")
	_Write_CallTip("$ImGuiDragDropFlags_SourceAllowNullID", 				"$ImGuiDragDropFlags_SourceAllowNullID")
	_Write_CallTip("$ImGuiDragDropFlags_SourceExtern", 						"$ImGuiDragDropFlags_SourceExtern")
	_Write_CallTip("$ImGuiDragDropFlags_SourceAutoExpirePayload", 			"$ImGuiDragDropFlags_SourceAutoExpirePayload")
	_Write_CallTip("$ImGuiDragDropFlags_AcceptBeforeDelivery", 				"$ImGuiDragDropFlags_AcceptBeforeDelivery")
	_Write_CallTip("$ImGuiDragDropFlags_AcceptNoDrawDefaultRect", 			"$ImGuiDragDropFlags_AcceptNoDrawDefaultRect")
	_Write_CallTip("$ImGuiDragDropFlags_AcceptNoPreviewTooltip", 			"$ImGuiDragDropFlags_AcceptNoPreviewTooltip")
	_Write_CallTip("$ImGuiDragDropFlags_AcceptPeekOnly", 					"$ImGuiDragDropFlags_AcceptPeekOnly")
	_Write_CallTip("$ImGuiDataType_S8", 									"$ImGuiDataType_S8")
	_Write_CallTip("$ImGuiDataType_U8", 									"$ImGuiDataType_U8")
	_Write_CallTip("$ImGuiDataType_S16", 									"$ImGuiDataType_S16")
	_Write_CallTip("$ImGuiDataType_U16", 									"$ImGuiDataType_U16")
	_Write_CallTip("$ImGuiDataType_S32", 									"$ImGuiDataType_S32")
	_Write_CallTip("$ImGuiDataType_U32", 									"$ImGuiDataType_U32")
	_Write_CallTip("$ImGuiDataType_S64", 									"$ImGuiDataType_S64")
	_Write_CallTip("$ImGuiDataType_U64", 									"$ImGuiDataType_U64")
	_Write_CallTip("$ImGuiDataType_Float", 									"$ImGuiDataType_Float")
	_Write_CallTip("$ImGuiDataType_Double", 								"$ImGuiDataType_Double")
	_Write_CallTip("$ImGuiDir_None", 										"$ImGuiDir_None")
	_Write_CallTip("$ImGuiDir_Left", 										"$ImGuiDir_Left")
	_Write_CallTip("$ImGuiDir_Right", 										"$ImGuiDir_Right")
	_Write_CallTip("$ImGuiDir_Up", 											"$ImGuiDir_Up")
	_Write_CallTip("$ImGuiDir_Down", 										"$ImGuiDir_Down")
	_Write_CallTip("$ImGuiKey_Tab", 										"$ImGuiKey_Tab")
	_Write_CallTip("$ImGuiKey_LeftArrow", 									"$ImGuiKey_LeftArrow")
	_Write_CallTip("$ImGuiKey_RightArrow", 									"$ImGuiKey_RightArrow")
	_Write_CallTip("$ImGuiKey_UpArrow", 									"$ImGuiKey_UpArrow")
	_Write_CallTip("$ImGuiKey_DownArrow", 									"$ImGuiKey_DownArrow")
	_Write_CallTip("$ImGuiKey_PageUp", 										"$ImGuiKey_PageUp")
	_Write_CallTip("$ImGuiKey_PageDown", 									"$ImGuiKey_PageDown")
	_Write_CallTip("$ImGuiKey_Home", 										"$ImGuiKey_Home")
	_Write_CallTip("$ImGuiKey_End", 										"$ImGuiKey_End")
	_Write_CallTip("$ImGuiKey_Insert", 										"$ImGuiKey_Insert")
	_Write_CallTip("$ImGuiKey_Delete", 										"$ImGuiKey_Delete")
	_Write_CallTip("$ImGuiKey_Backspace", 									"$ImGuiKey_Backspace")
	_Write_CallTip("$ImGuiKey_Space", 										"$ImGuiKey_Space")
	_Write_CallTip("$ImGuiKey_Enter", 										"$ImGuiKey_Enter")
	_Write_CallTip("$ImGuiKey_Escape", 										"$ImGuiKey_Escape")
	_Write_CallTip("$ImGuiKey_KeyPadEnter", 								"$ImGuiKey_KeyPadEnter")
	_Write_CallTip("$ImGuiKey_A", 											"$ImGuiKey_A")
	_Write_CallTip("$ImGuiKey_C", 											"$ImGuiKey_C")
	_Write_CallTip("$ImGuiKey_V", 											"$ImGuiKey_V")
	_Write_CallTip("$ImGuiKey_X", 											"$ImGuiKey_X")
	_Write_CallTip("$ImGuiKey_Y", 											"$ImGuiKey_Y")
	_Write_CallTip("$ImGuiKey_Z", 											"$ImGuiKey_Z")
	_Write_CallTip("$ImGuiKeyModFlags_None", 								"$ImGuiKeyModFlags_None")
	_Write_CallTip("$ImGuiKeyModFlags_Ctrl", 								"$ImGuiKeyModFlags_Ctrl")
	_Write_CallTip("$ImGuiKeyModFlags_Shift", 								"$ImGuiKeyModFlags_Shift")
	_Write_CallTip("$ImGuiKeyModFlags_Alt", 								"$ImGuiKeyModFlags_Alt")
	_Write_CallTip("$ImGuiKeyModFlags_Super", 								"$ImGuiKeyModFlags_Super")
	_Write_CallTip("$ImGuiNavInput_Activate",								"$ImGuiNavInput_Activate")
	_Write_CallTip("$ImGuiNavInput_Cancel", 								"$ImGuiNavInput_Cancel")
	_Write_CallTip("$ImGuiNavInput_Input",									"$ImGuiNavInput_Input")
	_Write_CallTip("$ImGuiNavInput_Menu", 									"$ImGuiNavInput_Menu")
	_Write_CallTip("$ImGuiNavInput_DpadLeft", 								"$ImGuiNavInput_DpadLeft")
	_Write_CallTip("$ImGuiNavInput_DpadRight", 								"$ImGuiNavInput_DpadRight")
	_Write_CallTip("$ImGuiNavInput_DpadUp", 								"$ImGuiNavInput_DpadUp")
	_Write_CallTip("$ImGuiNavInput_DpadDown", 								"$ImGuiNavInput_DpadDown")
	_Write_CallTip("$ImGuiNavInput_LStickLeft", 							"$ImGuiNavInput_LStickLeft")
	_Write_CallTip("$ImGuiNavInput_LStickRight", 							"$ImGuiNavInput_LStickRight")
	_Write_CallTip("$ImGuiNavInput_LStickUp", 								"$ImGuiNavInput_LStickUp")
	_Write_CallTip("$ImGuiNavInput_LStickDown", 							"$ImGuiNavInput_LStickDown")
	_Write_CallTip("$ImGuiNavInput_FocusPrev", 								"$ImGuiNavInput_FocusPrev")
	_Write_CallTip("$ImGuiNavInput_FocusNext", 								"$ImGuiNavInput_FocusNext")
	_Write_CallTip("$ImGuiNavInput_TweakSlow", 								"$ImGuiNavInput_TweakSlow")
	_Write_CallTip("$ImGuiNavInput_TweakFast", 								"$ImGuiNavInput_TweakFast")
	_Write_CallTip("$ImGuiNavInput_KeyMenu_", 								"$ImGuiNavInput_KeyMenu_")
	_Write_CallTip("$ImGuiNavInput_KeyLeft_", 								"$ImGuiNavInput_KeyLeft_")
	_Write_CallTip("$ImGuiNavInput_KeyRight_", 								"$ImGuiNavInput_KeyRight_")
	_Write_CallTip("$ImGuiNavInput_KeyUp_", 								"$ImGuiNavInput_KeyUp_")
	_Write_CallTip("$ImGuiNavInput_KeyDown_", 								"$ImGuiNavInput_KeyDown_")
	_Write_CallTip("$ImGuiNavInput_InternalStart_", 						"$ImGuiNavInput_InternalStart_")
	_Write_CallTip("$ImGuiConfigFlags_None", 								"$ImGuiConfigFlags_None")
	_Write_CallTip("$ImGuiConfigFlags_NavEnableKeyboard", 					"$ImGuiConfigFlags_NavEnableKeyboard")
	_Write_CallTip("$ImGuiConfigFlags_NavEnableGamepad", 					"$ImGuiConfigFlags_NavEnableGamepad")
	_Write_CallTip("$ImGuiConfigFlags_NavEnableSetMousePos", 				"$ImGuiConfigFlags_NavEnableSetMousePos")
	_Write_CallTip("$ImGuiConfigFlags_NavNoCaptureKeyboard", 				"$ImGuiConfigFlags_NavNoCaptureKeyboard")
	_Write_CallTip("$ImGuiConfigFlags_NoMouse", 							"$ImGuiConfigFlags_NoMouse")
	_Write_CallTip("$ImGuiConfigFlags_NoMouseCursorChange", 				"$ImGuiConfigFlags_NoMouseCursorChange")
	_Write_CallTip("$ImGuiConfigFlags_DockingEnable", 						"$ImGuiConfigFlags_DockingEnable")
	_Write_CallTip("$ImGuiConfigFlags_ViewportsEnable", 					"$ImGuiConfigFlags_ViewportsEnable")
	_Write_CallTip("$ImGuiConfigFlags_DpiEnableScaleViewports=", 			"$ImGuiConfigFlags_DpiEnableScaleViewports=")
	_Write_CallTip("$ImGuiConfigFlags_DpiEnableScaleFonts", 				"$ImGuiConfigFlags_DpiEnableScaleFonts")
	_Write_CallTip("$ImGuiConfigFlags_IsSRGB", 								"$ImGuiConfigFlags_IsSRGB")
	_Write_CallTip("$ImGuiConfigFlags_IsTouchScreen", 						"$ImGuiConfigFlags_IsTouchScreen")
	_Write_CallTip("$ImGuiBackendFlags_None", 								"$ImGuiBackendFlags_None")
	_Write_CallTip("$ImGuiBackendFlags_HasGamepad", 						"$ImGuiBackendFlags_HasGamepad")
	_Write_CallTip("$ImGuiBackendFlags_HasMouseCursors", 					"$ImGuiBackendFlags_HasMouseCursors")
	_Write_CallTip("$ImGuiBackendFlags_HasSetMousePos", 					"$ImGuiBackendFlags_HasSetMousePos")
	_Write_CallTip("$ImGuiBackendFlags_RendererHasVtxOffset", 				"$ImGuiBackendFlags_RendererHasVtxOffset")
	_Write_CallTip("$ImGuiBackendFlags_PlatformHasViewports", 				"$ImGuiBackendFlags_PlatformHasViewports")
	_Write_CallTip("$ImGuiBackendFlags_HasMouseHoveredViewport=", 			"$ImGuiBackendFlags_HasMouseHoveredViewport=")
	_Write_CallTip("$ImGuiBackendFlags_RendererHasViewports", 				"$ImGuiBackendFlags_RendererHasViewports")
	_Write_CallTip("$ImGuiCol_Text", 										"$ImGuiCol_Text")
	_Write_CallTip("$ImGuiCol_TextDisabled", 								"$ImGuiCol_TextDisabled")
	_Write_CallTip("$ImGuiCol_WindowBg", 									"$ImGuiCol_WindowBg")
	_Write_CallTip("$ImGuiCol_ChildBg", 									"$ImGuiCol_ChildBg")
	_Write_CallTip("$ImGuiCol_PopupBg", 									"$ImGuiCol_PopupBg")
	_Write_CallTip("$ImGuiCol_Border",										"$ImGuiCol_Border")
	_Write_CallTip("$ImGuiCol_BorderShadow", 								"$ImGuiCol_BorderShadow")
	_Write_CallTip("$ImGuiCol_FrameBg", 									"$ImGuiCol_FrameBg")
	_Write_CallTip("$ImGuiCol_FrameBgHovered", 								"$ImGuiCol_FrameBgHovered")
	_Write_CallTip("$ImGuiCol_FrameBgActive", 								"$ImGuiCol_FrameBgActive")
	_Write_CallTip("$ImGuiCol_TitleBg", 									"$ImGuiCol_TitleBg")
	_Write_CallTip("$ImGuiCol_TitleBgActive", 								"$ImGuiCol_TitleBgActive")
	_Write_CallTip("$ImGuiCol_TitleBgCollapsed", 							"$ImGuiCol_TitleBgCollapsed")
	_Write_CallTip("$ImGuiCol_MenuBarBg", 									"$ImGuiCol_MenuBarBg")
	_Write_CallTip("$ImGuiCol_ScrollbarBg", 								"$ImGuiCol_ScrollbarBg")
	_Write_CallTip("$ImGuiCol_ScrollbarGrab",								"$ImGuiCol_ScrollbarGrab")
	_Write_CallTip("$ImGuiCol_ScrollbarGrabHovered", 						"$ImGuiCol_ScrollbarGrabHovered")
	_Write_CallTip("$ImGuiCol_ScrollbarGrabActive", 						"$ImGuiCol_ScrollbarGrabActive")
	_Write_CallTip("$ImGuiCol_CheckMark", 									"$ImGuiCol_CheckMark")
	_Write_CallTip("$ImGuiCol_SliderGrab", 									"$ImGuiCol_SliderGrab")
	_Write_CallTip("$ImGuiCol_SliderGrabActive", 							"$ImGuiCol_SliderGrabActive")
	_Write_CallTip("$ImGuiCol_Button", 										"$ImGuiCol_Button")
	_Write_CallTip("$ImGuiCol_ButtonHovered", 								"$ImGuiCol_ButtonHovered")
	_Write_CallTip("$ImGuiCol_ButtonActive", 								"$ImGuiCol_ButtonActive")
	_Write_CallTip("$ImGuiCol_Header", 										"$ImGuiCol_Header")
	_Write_CallTip("$ImGuiCol_HeaderHovered", 								"$ImGuiCol_HeaderHovered")
	_Write_CallTip("$ImGuiCol_HeaderActive", 								"$ImGuiCol_HeaderActive")
	_Write_CallTip("$ImGuiCol_Separator", 									"$ImGuiCol_Separator")
	_Write_CallTip("$ImGuiCol_SeparatorHovered", 							"$ImGuiCol_SeparatorHovered")
	_Write_CallTip("$ImGuiCol_SeparatorActive", 							"$ImGuiCol_SeparatorActive")
	_Write_CallTip("$ImGuiCol_ResizeGrip", 									"$ImGuiCol_ResizeGrip")
	_Write_CallTip("$ImGuiCol_ResizeGripHovered", 							"$ImGuiCol_ResizeGripHovered")
	_Write_CallTip("$ImGuiCol_ResizeGripActive", 							"$ImGuiCol_ResizeGripActive")
	_Write_CallTip("$ImGuiCol_Tab", 										"$ImGuiCol_Tab")
	_Write_CallTip("$ImGuiCol_TabHovered", 									"$ImGuiCol_TabHovered")
	_Write_CallTip("$ImGuiCol_TabActive", 									"$ImGuiCol_TabActive")
	_Write_CallTip("$ImGuiCol_TabUnfocused", 								"$ImGuiCol_TabUnfocused")
	_Write_CallTip("$ImGuiCol_TabUnfocusedActive", 							"$ImGuiCol_TabUnfocusedActive")
	_Write_CallTip("$ImGuiCol_DockingPreview", 								"$ImGuiCol_DockingPreview")
	_Write_CallTip("$ImGuiCol_DockingEmptyBg", 								"$ImGuiCol_DockingEmptyBg")
	_Write_CallTip("$ImGuiCol_PlotLines", 									"$ImGuiCol_PlotLines")
	_Write_CallTip("$ImGuiCol_PlotLinesHovered", 							"$ImGuiCol_PlotLinesHovered")
	_Write_CallTip("$ImGuiCol_PlotHistogram", 								"$ImGuiCol_PlotHistogram")
	_Write_CallTip("$ImGuiCol_PlotHistogramHovered", 						"$ImGuiCol_PlotHistogramHovered")
	_Write_CallTip("$ImGuiCol_TextSelectedBg", 								"$ImGuiCol_TextSelectedBg")
	_Write_CallTip("$ImGuiCol_DragDropTarget", 								"$ImGuiCol_DragDropTarget")
	_Write_CallTip("$ImGuiCol_NavHighlight", 								"$ImGuiCol_NavHighlight")
	_Write_CallTip("$ImGuiCol_NavWindowingHighlight", 						"$ImGuiCol_NavWindowingHighlight")
	_Write_CallTip("$ImGuiCol_NavWindowingDimBg", 							"$ImGuiCol_NavWindowingDimBg")
	_Write_CallTip("$ImGuiCol_ModalWindowDimBg", 							"$ImGuiCol_ModalWindowDimBg")
	_Write_CallTip("$ImGuiCol_DockingPreview_1", 							"$ImGuiCol_DockingPreview_1")
	_Write_CallTip("$ImGuiCol_DockingOutLine", 								"$ImGuiCol_DockingOutLine")
	_Write_CallTip("$ImGuiCol_DockingLine", 								"$ImGuiCol_DockingLine")
	_Write_CallTip("$ImGuiStyleVar_Alpha", 									"$ImGuiStyleVar_Alpha")
	_Write_CallTip("$ImGuiStyleVar_WindowPadding", 							"$ImGuiStyleVar_WindowPadding")
	_Write_CallTip("$ImGuiStyleVar_WindowRounding", 						"$ImGuiStyleVar_WindowRounding")
	_Write_CallTip("$ImGuiStyleVar_WindowBorderSize", 						"$ImGuiStyleVar_WindowBorderSize")
	_Write_CallTip("$ImGuiStyleVar_WindowMinSize", 							"$ImGuiStyleVar_WindowMinSize")
	_Write_CallTip("$ImGuiStyleVar_WindowTitleAlign", 						"$ImGuiStyleVar_WindowTitleAlign")
	_Write_CallTip("$ImGuiStyleVar_ChildRounding", 							"$ImGuiStyleVar_ChildRounding")
	_Write_CallTip("$ImGuiStyleVar_ChildBorderSize", 						"$ImGuiStyleVar_ChildBorderSize")
	_Write_CallTip("$ImGuiStyleVar_PopupRounding", 							"$ImGuiStyleVar_PopupRounding")
	_Write_CallTip("$ImGuiStyleVar_PopupBorderSize", 						"$ImGuiStyleVar_PopupBorderSize")
	_Write_CallTip("$ImGuiStyleVar_FramePadding", 							"$ImGuiStyleVar_FramePadding")
	_Write_CallTip("$ImGuiStyleVar_FrameRounding", 							"$ImGuiStyleVar_FrameRounding")
	_Write_CallTip("$ImGuiStyleVar_FrameBorderSize", 						"$ImGuiStyleVar_FrameBorderSize")
	_Write_CallTip("$ImGuiStyleVar_ItemSpacing", 							"$ImGuiStyleVar_ItemSpacing")
	_Write_CallTip("$ImGuiStyleVar_ItemInnerSpacing", 						"$ImGuiStyleVar_ItemInnerSpacing")
	_Write_CallTip("$ImGuiStyleVar_IndentSpacing", 							"$ImGuiStyleVar_IndentSpacing")
	_Write_CallTip("$ImGuiStyleVar_ScrollbarSize", 							"$ImGuiStyleVar_ScrollbarSize")
	_Write_CallTip("$ImGuiStyleVar_ScrollbarRounding", 						"$ImGuiStyleVar_ScrollbarRounding")
	_Write_CallTip("$ImGuiStyleVar_GrabMinSize", 							"$ImGuiStyleVar_GrabMinSize")
	_Write_CallTip("$ImGuiStyleVar_GrabRounding", 							"$ImGuiStyleVar_GrabRounding")
	_Write_CallTip("$ImGuiStyleVar_TabRounding", 							"$ImGuiStyleVar_TabRounding")
	_Write_CallTip("$ImGuiStyleVar_ButtonTextAlign", 						"$ImGuiStyleVar_ButtonTextAlign")
	_Write_CallTip("$ImGuiStyleVar_SelectableTextAlign", 					"$ImGuiStyleVar_SelectableTextAlign")
	_Write_CallTip("$ImGuiColorEditFlags_None", 							"$ImGuiColorEditFlags_None")
	_Write_CallTip("$ImGuiColorEditFlags_NoAlpha", 							"$ImGuiColorEditFlags_NoAlpha")
	_Write_CallTip("$ImGuiColorEditFlags_NoPicker", 						"$ImGuiColorEditFlags_NoPicker")
	_Write_CallTip("$ImGuiColorEditFlags_NoOptions", 						"$ImGuiColorEditFlags_NoOptions")
	_Write_CallTip("$ImGuiColorEditFlags_NoSmallPreview", 					"$ImGuiColorEditFlags_NoSmallPreview")
	_Write_CallTip("$ImGuiColorEditFlags_NoInputs", 						"$ImGuiColorEditFlags_NoInputs")
	_Write_CallTip("$ImGuiColorEditFlags_NoTooltip", 						"$ImGuiColorEditFlags_NoTooltip")
	_Write_CallTip("$ImGuiColorEditFlags_NoLabel", 							"$ImGuiColorEditFlags_NoLabel")
	_Write_CallTip("$ImGuiColorEditFlags_NoSidePreview", 					"$ImGuiColorEditFlags_NoSidePreview")
	_Write_CallTip("$ImGuiColorEditFlags_NoDragDrop", 						"$ImGuiColorEditFlags_NoDragDrop")
	_Write_CallTip("$ImGuiColorEditFlags_NoBorder", 						"$ImGuiColorEditFlags_NoBorder")
	_Write_CallTip("$ImGuiColorEditFlags_AlphaBar", 						"$ImGuiColorEditFlags_AlphaBar")
	_Write_CallTip("$ImGuiColorEditFlags_AlphaPreview", 					"$ImGuiColorEditFlags_AlphaPreview")
	_Write_CallTip("$ImGuiColorEditFlags_AlphaPreviewHalf=", 				"$ImGuiColorEditFlags_AlphaPreviewHalf=")
	_Write_CallTip("$ImGuiColorEditFlags_HDR", 								"$ImGuiColorEditFlags_HDR")
	_Write_CallTip("$ImGuiColorEditFlags_DisplayRGB", 						"$ImGuiColorEditFlags_DisplayRGB")
	_Write_CallTip("$ImGuiColorEditFlags_DisplayHSV", 						"$ImGuiColorEditFlags_DisplayHSV")
	_Write_CallTip("$ImGuiColorEditFlags_DisplayHex", 						"$ImGuiColorEditFlags_DisplayHex")
	_Write_CallTip("$ImGuiColorEditFlags_Uint8", 							"$ImGuiColorEditFlags_Uint8")
	_Write_CallTip("$ImGuiColorEditFlags_Float", 							"$ImGuiColorEditFlags_Float")
	_Write_CallTip("$ImGuiColorEditFlags_PickerHueBar", 					"$ImGuiColorEditFlags_PickerHueBar")
	_Write_CallTip("$ImGuiColorEditFlags_PickerHueWheel", 					"$ImGuiColorEditFlags_PickerHueWheel")
	_Write_CallTip("$ImGuiColorEditFlags_InputRGB", 						"$ImGuiColorEditFlags_InputRGB")
	_Write_CallTip("$ImGuiColorEditFlags_InputHSV", 						"$ImGuiColorEditFlags_InputHSV")
	_Write_CallTip("$ImGuiColorEditFlags__OptionsDefault", 					"$ImGuiColorEditFlags__OptionsDefault")
	_Write_CallTip("$ImGuiColorEditFlags__DisplayMask", 					"$ImGuiColorEditFlags__DisplayMask")
	_Write_CallTip("$ImGuiColorEditFlags__DataTypeMask", 					"$ImGuiColorEditFlags__DataTypeMask")
	_Write_CallTip("$ImGuiColorEditFlags__PickerMask", 						"$ImGuiColorEditFlags__PickerMask")
	_Write_CallTip("$ImGuiColorEditFlags__InputMask", 						"$ImGuiColorEditFlags__InputMask")
	_Write_CallTip("$ImGuiMouseButton_Left", 								"$ImGuiMouseButton_Left")
	_Write_CallTip("$ImGuiMouseButton_Right", 								"$ImGuiMouseButton_Right")
	_Write_CallTip("$ImGuiMouseButton_Middle", 								"$ImGuiMouseButton_Middle")
	_Write_CallTip("$ImGuiMouseCursor_None", 								"$ImGuiMouseCursor_None")
	_Write_CallTip("$ImGuiMouseCursor_Arrow", 								"$ImGuiMouseCursor_Arrow")
	_Write_CallTip("$ImGuiMouseCursor_TextInput", 							"$ImGuiMouseCursor_TextInput")
	_Write_CallTip("$ImGuiMouseCursor_ResizeAll", 							"$ImGuiMouseCursor_ResizeAll")
	_Write_CallTip("$ImGuiMouseCursor_ResizeNS", 							"$ImGuiMouseCursor_ResizeNS")
	_Write_CallTip("$ImGuiMouseCursor_ResizeEW", 							"$ImGuiMouseCursor_ResizeEW")
	_Write_CallTip("$ImGuiMouseCursor_ResizeNESW", 							"$ImGuiMouseCursor_ResizeNESW")
	_Write_CallTip("$ImGuiMouseCursor_ResizeNWSE", 							"$ImGuiMouseCursor_ResizeNWSE")
	_Write_CallTip("$ImGuiMouseCursor_Hand", 								"$ImGuiMouseCursor_Hand")
	_Write_CallTip("$ImGuiMouseCursor_NotAllowed", 							"$ImGuiMouseCursor_NotAllowed")
	_Write_CallTip("$ImGuiCond_None", 										"$ImGuiCond_None")
	_Write_CallTip("$ImGuiCond_Always", 									"$ImGuiCond_Always")
	_Write_CallTip("$ImGuiCond_Once", 										"$ImGuiCond_Once")
	_Write_CallTip("$ImGuiCond_FirstUseEver", 								"$ImGuiCond_FirstUseEver")
	_Write_CallTip("$ImGuiCond_Appearing", 									"$ImGuiCond_Appearing")
	_Write_CallTip("$ImDrawCornerFlags_None", 								"$ImDrawCornerFlags_None")
	_Write_CallTip("$ImDrawCornerFlags_TopLeft", 							"$ImDrawCornerFlags_TopLeft")
	_Write_CallTip("$ImDrawCornerFlags_TopRight", 							"$ImDrawCornerFlags_TopRight")
	_Write_CallTip("$ImDrawCornerFlags_BotLeft", 							"$ImDrawCornerFlags_BotLeft")
	_Write_CallTip("$ImDrawCornerFlags_BotRight", 							"$ImDrawCornerFlags_BotRight")
	_Write_CallTip("$ImDrawCornerFlags_Top", 								"$ImDrawCornerFlags_Top")
	_Write_CallTip("$ImDrawCornerFlags_Bot", 								"$ImDrawCornerFlags_Bot")
	_Write_CallTip("$ImDrawCornerFlags_Left", 								"$ImDrawCornerFlags_Left")
	_Write_CallTip("$ImDrawCornerFlags_Right", 								"$ImDrawCornerFlags_Right")
	_Write_CallTip("$ImDrawCornerFlags_All", 								"$ImDrawCornerFlags_All")
	_Write_CallTip("$ImDrawListFlags_None", 								"$ImDrawListFlags_None")
	_Write_CallTip("$ImDrawListFlags_AntiAliasedLines", 					"$ImDrawListFlags_AntiAliasedLines")
	_Write_CallTip("$ImDrawListFlags_AntiAliasedFill", 						"$ImDrawListFlags_AntiAliasedFill")
	_Write_CallTip("$ImDrawListFlags_AllowVtxOffset", 						"$ImDrawListFlags_AllowVtxOffset")

EndFunc

Func _ChangeUDFColor()
	Local $aCurKeyValue, $aKey = "style.au3.16", $aKeyValue = "0080FF"
	Local $RegKey = StringReplace($aKey, "$", "\$")
	$RegKey = StringReplace($RegKey, "(", "\(")
	$RegKey = StringReplace($RegKey, ")", "\)")
	$aCurKeyValue = StringRegExp(@CRLF & $SciTEUser_Content, "(?i)\r\n[\s]*" & $RegKey & "[\s]*=(.*?),", 3)

	If UBound($aCurKeyValue) Then
		If $aCurKeyValue[0] <> $aKeyValue Then
			$aKeyValue = StringReplace($aKeyValue, "\", "\\")
			$SciTEUser_Content = StringMid(StringRegExpReplace(@CRLF & $SciTEUser_Content, "(?i)\r\n[\s]*" & $RegKey & "[\s]*=(.*?),", @CRLF & $RegKey & "=fore:#" & $aKeyValue & ","), 3)
		EndIf
	Else
		$SciTEUser_Content &= $aKey & "=" & $aKeyValue & @CRLF
	EndIf
	FileDelete($SciTEUserDir & "\SciTEUser.properties")
	FileWrite($SciTEUserDir & "\SciTEUser.properties", StringTrimRight($SciTEUser_Content, 2))
EndFunc

Func SendSciTE_Command($My_Hwnd, $SciTE_hwnd, $sCmd)
	Local $WM_COPYDATA = 74
	Local $CmdStruct = DllStructCreate('Char[' & StringLen($sCmd) + 1 & ']')
	;ConsoleWrite('-->' & $sCmd & @lf )
	DllStructSetData($CmdStruct, 1, $sCmd)
	Local $COPYDATA = DllStructCreate('Ptr;DWord;Ptr')
	DllStructSetData($COPYDATA, 1, 1)
	DllStructSetData($COPYDATA, 2, StringLen($sCmd) + 1)
	DllStructSetData($COPYDATA, 3, DllStructGetPtr($CmdStruct))
	DllCall('User32.dll', 'None', 'SendMessage', 'HWnd', $SciTE_hwnd, _
			'Int', $WM_COPYDATA, 'HWnd', $My_Hwnd, _
			'Ptr', DllStructGetPtr($COPYDATA))
EndFunc   ;==>SendSciTE_Command

Func _GetAutoitPath()
	If EnvGet("SCITE_USERHOME") <> "" And FileExists(EnvGet("SCITE_USERHOME")) Then
		$SciTEUserDir = EnvGet("SCITE_USERHOME")
	ElseIf EnvGet("SCITE_HOME") <> "" And FileExists(EnvGet("SCITE_HOME")) Then
		$SciTEUserDir = EnvGet("SCITE_HOME")
	Else
		$SciTEUserDir = @UserProfileDir ; original sciTE default location
	EndIf

	If StringInStr(@ScriptDir, @ProgramFilesDir) Then
		If Not FileExists($SciTEUserDir & "\SciTEConfig\UCTMan") Then DirCreate(@AppDataDir & "\SciTEConfig\UCTMan")
		$sUserPath = $SciTEUserDir & "\SciTEConfig\UCTMan\UCT.txt"
	Else
		$sUserPath = @ScriptDir & "\UCT.txt"
	EndIf
EndFunc

Func GetStr()
	Local $str = ClipGet()
	Local $lines = StringSplit($str, @CRLF, 1)

	For $i = 1 To $lines[0]

		$lines[$i] = StringStripWS($lines[$i], 1)

		If StringLeft($lines[$i], 4) = "Func" Then
			Local $func_name = StringStripWS(StringRegExp($lines[$i], 'Func(.*?)\(', 1)[0], 7)
			$lines[$i] = StringStripWS(StringTrimLeft($lines[$i], 4), 7)
			ConsoleWrite('_Write_CallTip("' & $func_name & '", 				' & "'" & $lines[$i] & " ')" & @CRLF)
		EndIf
	Next
EndFunc

Func GetVar()
	Local $str = ClipGet()
	Local $lines = StringSplit($str, @CRLF, 1)
	For $i = 1 To $lines[0]
		Local $a = StringRegExp($lines[$i], '\$(.*?) ', 1)
		If IsArray($a) Then ConsoleWrite('_Write_CallTip("$' & $a[0] & '", 				"$' & $a[0] & '")' & @CRLF)
	Next
EndFunc

Func _Write_CallTip( $sUDF_Title, $sUDF_Text)
	Local $iCallTip_Line = -1

	If StringLeft($sUDF_Text, 1) <> "$" Then
		If StringRight($sUDF_Text, 1) = " " Then
			$sUDF_Text &= '#include <ImGui.au3>'
		ElseIf StringRight($sUDF_Text, 1) <> '.' Then
			$sUDF_Text &= '.'
		EndIf
	EndIf

	For $i = 1 To $aCallTip[0]
		If (StringLeft($sUDF_Title, 1) = "$" And $aCallTip[$i] = $sUDF_Text) Or _
			(StringLeft($aCallTip[$i], StringLen($sUDF_Title)+1) = $sUDF_Title & "(") Then
			$iCallTip_Line = $i
			ExitLoop
		EndIf
	Next
	If $iCallTip_Line = -1 Then
		; If not found then add
		$i_Imported += 1
		_ArrayAdd($aCallTip, $sUDF_Text)
		$aCallTip[0] += 1
		ConsoleWrite("Imported: " & $sUDF_Text & @CRLF)
	Else
		If $sUDF_Text <> $aCallTip[$iCallTip_Line] Then
			$i_Updated += 1
			$aCallTip[$iCallTip_Line] = $sUDF_Text
			ConsoleWrite("Updated: " & $sUDF_Text & @CRLF)
		EndIf
	EndIf
EndFunc   ;==>_Write_CallTip

Func _Save_Exit_UCT()

	Local $aSplit

	; Save backups and write changed files

	; Calltip file
	FileMove($sCallTipPath, $sCallTipPath & ".bak", 1)
	_FileWriteFromArray($sCallTipPath, $aCallTip, 1)
	; Keyword file
	FileCopy($sKeyWordPath, $sKeyWordPath & ".bak", 1)
	Local $sUser_KeyWord = ""
	Local $sLine = "au3.keywords.user.udfs="
	For $i = 1 To $aCallTip[0]
		$aSplit = StringSplit($aCallTip[$i], "(")
		If Not @error Then
			$sLine &= StringLower($aSplit[1])
			If $i = $aCallTip[0] Then
				$sUser_KeyWord &= $sLine
				ExitLoop
			Else
				If StringLen($sLine) > 100 Then
					$sLine &= " \" & @CRLF
					$sUser_KeyWord &= $sLine
					$sLine = @TAB
				Else
					$sLine &= " "
				EndIf
			EndIf
		EndIf
	Next
	Local $cFile = FileOpen($sKeyWordPath, 2)
	FileWrite($cFile, $sUser_KeyWord)
	FileClose($cFile)

	; Backup file
	FileMove($sUserPath, $sUserPath & ".bak", 1)
	_FileWriteFromArray($sUserPath, $aCallTip, 1)
EndFunc